### ISSUE TITLE
Jupyter setup failure since April 5

### ISSUE THREAD

**Issue by vadym-wix** [GoogleCloudPlatform/dataproc-initialization-actions#102]
Hi, since today started to encounter jupyter setup failure.

 For the previous 2 months everything worked just fine

Now, I'm getting an error:

```
jupyter-1.0.0-   0% |                              | ETA:  --:--:--   0.00  B/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00   5.96 MB/s
jupyter-1.0.0- 100% |###############################| Time: 0:00:00   3.71 MB/s
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 112, in RunMain
    import gslib.__main__
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 39, in <module>
    import boto
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/boto_config.py", line 29, in <module>
    from google_compute_engine import config_manager
ImportError: No module named google_compute_engine
```

**Comment by dennishuo** [comment]
I got stuck at first on the `ImportError: No module named google_compute_engine` error since I couldn't figure out how it ever worked :)

Basically, the clobbering of `PATH` to have conda first always breaks `gsutil`, so the little `gsutil stat` trick trying to fetch notebooks from GCS just never actually worked (but also was untested and apparently unused).

But it's in a conditional so that's actually just a red herring. @nehalecky is correct that https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/103 should resolve this.

**Comment by dennishuo** [comment]
Merged https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/103 - should work out of the box once again.

**Comment by nehalecky** [comment]
@dennishuo, thanks for the details on that `ImportError`. Is `gsutil` the only component of glcoud sdk that doesn't play nice with conda, or are there others? Any more details on that would be appreciated as we're (@jeffkpayne) currently updating a Docker image that has both. 😄 

Also, any more info on the use of Docker containers in Dataproc? :)

Thanks again!

**Comment by dennishuo** [comment]
@nehalecky To be honest we don't have much coverage of compatibility constraints between cloud SDK and conda, though at least in my experience gsutil tends to be more picky than base `gcloud` commands. A cursory check seems to show gcloud still working okay with conda installed and overridden on `PATH`. I'll be happy to hear about your findings if you do discover interesting quirks though!

Re: Docker containers, have you played around with the [datalab initialization action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/datalab) which uses a Docker container for the dev environment? It could be a worthwhile pattern to apply to other init actions.

I suppose the part that's less clear is whether there's a role for docker containers on worker nodes.

**Comment by jeffkpayne** [comment]
Yep, that `gsutil stat...` trick was definitely not well tested and, for other reasons, the goal that it was supposed to provide was never really utilized by us anyway.
