### ISSUE TITLE
Unable to run PySpark via Jupyter Notebook

### ISSUE THREAD

**Issue by vadym-wix** [GoogleCloudPlatform/dataproc-initialization-actions#105]
After Jupyter initialization script was updated, I am unable to run Spark scripts via Jupyter notebook, since PySpark kernel has python version 3.6.0

**Comment by dennishuo** [comment]
From https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/103 looks like it was the cleanup change which actually fixed the logic for choosing MINICONDA_VARIANT=3 (previously, the code was supposed to default to that, but instead appended a blank string, thus falling back to an older version IIUC).

The default behavior before was actually using Python 2 even though the intent was to default to 3.

In your case, do you have a hard dependency on Python 2, or are you running into the non-compatibility bug specific to Python 3.6 referred to in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/103 ?

I'll see about pushing a fix for both cases anyways

**Comment by dennishuo** [comment]
Okay, I tested successfully with the new updates, and against both Python 2 and Python 3 variants. Including actually running a pyspark job this time :)

    gcloud dataproc clusters create dhuo-jupyter-default \
         --initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh
    gcloud dataproc clusters create dhuo-jupyter-python2 \
         --initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh \
        --metadata MINICONDA_VARIANT=2

And the outputs:

    rdd = sc.parallelize(['Hello,', 'world!'])
    words = sorted(rdd.collect())
    print(words)
    import sys
    print(sys.version)

    ['Hello,', 'world!']
    3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Python2:

    rdd = sc.parallelize(['Hello,', 'world!'])
    words = sorted(rdd.collect())
    print(words)
    import sys
    print(sys.version)

    ['Hello,', 'world!']
    2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


For reference, if you want to fork the conda install scripts, you can deploy against them with something like:

    gcloud dataproc clusters create my-cluster \
        --initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh \
        --metadata INIT_ACTIONS_REPO=https://github.com/dennishuo/dataproc-initialization-actions.git,INIT_ACTIONS_BRANCH=pin-conda-version

**Comment by vadym-wix** [comment]
Yeah, now it works. Thank you!
