### ISSUE TITLE
conda/README.MD: MINICONDA variables must be metadata, not env vars

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/dataproc-initialization-actions#107]
`conda/README.MD` currently states: "users can easily config for targeted versions via the following env vars [...] `MINICONDA_VARIANT` [...] `MINICONDA_VER`"

However, as far as I can tell, `bootstrap-conda.sh` only reads from instance metadata. The first lines of the script currently set these variables with:

```shell
MINICONDA_VARIANT=$(/usr/share/google/get_metadata_value attributes/MINICONDA_VARIANT || true)
MINICONDA_VERSION=$(/usr/share/google/get_metadata_value attributes/MINICONDA_VERSION || true)
```

I think there are two possible fixes:

1. Change `README.MD` to say "instance metadata" instead of "env vars".
2. Change the script to prefer existing environment variables, then instance metadata, then the hard coded defaults.

(We ran into this since some update to something broke our Python 2 scripts, since it started installing Python 3 instead. We first tried setting the environment variables before running the script, before realizing that we need to set instance metadata keys instead)

**Comment by karth295** [comment]
Good catch -- thanks! I went with the first option.

**Comment by evanj** [comment]
AWESOME thanks!
