### ISSUE TITLE
Make Jupyter auto restart on reboot

### ISSUE THREAD

**Issue by dennishuo** [GoogleCloudPlatform/dataproc-initialization-actions#108]
Right now the init action only explicitly calls https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter/internal/launch-jupyter-kernel.sh in the initialization action, so if the master is rebooted, the jupyter server doesn't start up automatically. It should instead configure a systemd service to auto startup.

**Comment by sammcveety** [comment]
Any preference whether this .service file would inline the startup script or indirect to another file?

.service would be roughly:

[Unit]
Description=Start up Jupyter

[Service]
Type=oneshot
ExecStart=/usr/bin/launch_jupyter

[Install]
WantedBy=multi-user.target

**Comment by dennishuo** [comment]
Inline should be fine, it'd match the cloud-sql proxy: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/f22d7272d690bd48b9ea94bbf2f07ad464646236/cloud-sql-proxy/cloud-sql-proxy.sh#L115

Otherwise no strong preference either way.

**Comment by Jake-He** [comment]
Hi, I fixed the problem by connecting to master machine using ssh and created systemd service(followed @dennishuo  's stackoverflow comment).

1. go to /usr/lib/systemd/system
2. sudo su 
3. create a systemd unit file called "jupyter-notebook.service" with content

```
[Unit]
Description=Start Jupyter Notebook Server at reboot

[Service]
Type=simple
ExecStart=/opt/conda/bin/jupyter notebook --allow-root  --no-browser

[Install]
WantedBy=multi-user.target`
```

4. systemctl daemon-reload
5. systemctl enable jupyter-notebook.service
6. systemctl start jupyter-notebook.service

Next step will be to include above code into dataproc-initialization-actions.
Hope that helps.

**Comment by dennishuo** [comment]
Fixed in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/111 and https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/113
