### ISSUE TITLE
Kafka Script

### ISSUE THREAD

**Issue by namsoila** [GoogleCloudPlatform/dataproc-initialization-actions#119]
Running kafka.sh on Dataproc 1.1 leads to the following errors:

apt-get install -y kafka
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package kafka

apt-get install -y kafka-server
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package kafka-server
dpkg -l kafka-server
dpkg-query: no packages found matching kafka-server

**Comment by namsoila** [comment]
This is not the case when using the preview image for dataproc.

**Comment by dennishuo** [comment]
This is currently a known issue, as Kafka hadn't been building as part of the Dataproc 1.1 distribution. The next Dataproc 1.2 version and preview versions will support it. I added a note to the README to clarify this: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/kafka#important-notes
