### ISSUE TITLE
Ganglia init action does not work

### ISSUE THREAD

**Issue by karth295** [GoogleCloudPlatform/dataproc-initialization-actions#146]
```
gcloud beta dataproc clusters create my-cluster --initialization-actions=gs://dataproc-initialization-actions/ganglia/ganglia.sh
```

When I visit http://masterip via a SOCKS proxy, all I see is the default Apache web server landing page. Maybe the init action has misconfigured Apache?

**Comment by adam-stasiak** [comment]
@karth295 I tested this behavior using image version 1.2.27 and changes applied in #218 and did not have any problems with accessing UI.

**Comment by karth295** [comment]
Ah -- your comment in #228 correctly mentions you need to go to http://masterip/ganglia (rather than just /). So the init action was never broken. Thanks!
