### ISSUE TITLE
Update conda version

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/dataproc-initialization-actions#149]
I'm sometimes getting a flaky conda error when I try to start a new cluster.

In my startup script, I have:

`/opt/conda/bin/conda install -c anaconda basemap`

And it gives me the error described [here](https://github.com/conda/conda/issues/6042).

I believe updating the version of conda could solve the problem.

**Comment by karth295** [comment]
Sounds good to me -- the comment says pin Conda to 4.2 until Spark 2.2 is the default (which it now is).

In the mean time, it looks like you can set a metadata property to override the version: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/conda/bootstrap-conda.sh#L11.

`gcloud dataproc clusters create <name> ... --metadata MINICONDA_VERSION=some.version`

**Comment by bencaine1** [comment]
Great, thanks!
