### ISSUE TITLE
Expose init action API to a higher level provisioner / orchestration library?

### ISSUE THREAD

**Issue by nehalecky** [GoogleCloudPlatform/dataproc-initialization-actions#15]
I've been testing and using Dataproc for less than a week, so far, just awesome. Kudos to all the Google developers who made it a reality. I've recently been diving into custom provisioning of the cluster, and was able to quickly setup and connect to Jupyter using the IPython init action provided in this repo. Thanks, and it works great.

As the need for more refined control is always pressing (both myself and others #9, #8), it would be interesting to understand the decision behind the current architecture for Dataproc initialization actions, and how it compares to the roadmap for future functionality? 

In getting something off the ground, it's simple and effective to point to a bunch of bash shell scripts to perform provisioning. Admittedly this is what I do a majority of the time when setting up a local dev environment via provisioning a VM. In my case, however, one begins to realize that managing and passing state through a bunch of custom environment variables loses it's charm quickly, along with the need to parameterize through interactions with higher level objects become painfully apparent. :/

With this idea, was there any plan to expose Dataproc initialization actions to the provisioning capabilities of platforms like [Ansible](http://www.ansible.com/) or [Salt](http://saltstack.com/)? This would allow the *master* and *worker* nodes to simply be targeted with a playbook / formula, and allow the Dataproc end user the ability to tap into a large public resource of existing mechanisms for provisioning nodes with particular libraries and / or configurations.

Just a thought, and hope that it make sense. Thanks again for such a great resource. :)

**Comment by evilsoapbox** [comment]
Hello!

Apologies for the delayed response! We've been hard at work on some new features and our 12/16 release. Thanks for positive feedback - it's always **awesome** to hear things are working well.

In the long-term, we have a few things in mind. Unfortunately, I cannot go too much into our long-term roadmap (timing or commitment) but we've definitely discussed a few things:

* When initialization actions should run (before daemons, after, both?)
* Parameters to init actions
* Alternatives to initialization actions
* Templatizing clusters

I think we'll likely expand the richness of init actions (parameters, etc.) and they will be a core part of Dataproc in the long term. We are also thinking about ways we can expand deployment and provisioning in the future, especially if other frameworks (like Flink) become popular to use alongside Spark/Hadoop (Yarn + HDFS.) 

So, the tl;dr is it's something we have in mind. You're going to see better initialization action support in the future and in the longer-term, some more thinking (and possibly features) around deployment. You can always ping us at `dataproc-feedback@google` with ideas and suggestions - the dev team and I are on the list and always appreciate feedback, insights, and ideas. 

Cheers!

James
(Product Manager, Cloud Dataproc)

**Comment by nehalecky** [comment]
Hi James (@evilsoapbox), thank you for this thoughtful reply, and I look forward to what you are developing—sounds exciting! Hopefully along the way the open source community can also help contribute to expanding functionality of dataproc (through init actions or more). As dataproc already provides a solid service for computation using open computational frameworks like Spark, it just make sense to help out!

Just to clarify, would you prefer that future ideas and suggestions be emailed instead of posted as issues here? For instance, I was going to open an issue to ask for automated testing and had a few ideas for that. :)

Thanks again and cheers!
