### ISSUE TITLE
Add note to enable Google Cloud SQL API to cloud-sql-proxy readme

### ISSUE THREAD

**Issue by roscoejp** [GoogleCloudPlatform/dataproc-initialization-actions#153]
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/cloud-sql-proxy/README.MD

Should make a note in the Cloud SQL Proxy readme.md  that the Google Cloud SQL API (https://pantheon.corp.google.com/apis/library/sqladmin.googleapis.com/?q=sql)  must be enabled on the Google Cloud Platform Project or else you can't use the Cloud SQL Proxy from the Dataproc nodes.

**Comment by spark2ignite** [comment]
+1

**Comment by karth295** [comment]
I can add the note, but wouldn't you have had to enable the Cloud SQL API to create a Cloud SQL instance?
