### ISSUE TITLE
Oozie init action

### ISSUE THREAD

**Issue by evilsoapbox** [GoogleCloudPlatform/dataproc-initialization-actions#16]
We should have an Oozie init action. This is also going to be a prerequisite for getting Hue to work.

**Comment by Spark2Ignite** [comment]
+1

**Comment by evilsoapbox** [comment]
This is now included in [my most recent pull request](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/14).

**Comment by evilsoapbox** [comment]
This is now in the repo per pull request 14. Closing!
