### ISSUE TITLE
Permissions Error when attempting to read from mounted bucket

### ISSUE THREAD

**Issue by jmwoloso** [GoogleCloudPlatform/dataproc-initialization-actions#161]
Hello!

I created a 4 node spark cluster via `dataproc` and used the `jupyter notebook` initialization script (awesome, thanks for that!). 

I also installed `gcsfuse` on the cluster and I mount the buckets that I'm reading to and writing from to the master node in the cluster and that whole process works fine, however, when I attempt to get a listing of the files via python and jupyter notebook [`os.listdir(DATAPATH)`] i receive the following traceback in the notebook:

```
PermissionError                           Traceback (most recent call last)
<ipython-input-16-495c2f68a718> in <module>()
      9 
     10 # list of the apps
---> 11 TOP_LEVEL_FOLDERS=os.listdir(DATA_PATH)
     12 # TOP_LEVEL_FOLDERS="Action"
     13 

PermissionError: [Errno 13] Permission denied: '../../home/jason/buckets/input/InactiveAppsBackup/'

```

How do I start a notebook as my username instead of as root so I can read the files in the directory? Thanks!

**Comment by karth295** [comment]
FYI we're switching to storing notebooks in GCS in #156 , so take a look at that issue.

In the mean time here are a couple options:
1) You can copy the init action into your own GCS bucket and modify it so that the notebook starts as root (something like `sudo su -l jmwoloso ...`)
2) You can be root on the VM by putting `sudo` in front of any command, so you can just change the permissions of the relevant directories (something like `sudo chmod 777 -R PATH`)

**Comment by jmwoloso** [comment]
@karth295 Thank you for the reply. Option #2 from your suggestions does not work, I get `Permission denied` when I attempt to change the permissions of the mounted folders. Where exactly would I use Option #1 or which of the scripts would I edit?

**Comment by karth295** [comment]
I didn't actually test option 2, so fair enough.

Init actions are just arbitrary scripts hosted on GCS. By default, you might use `--initialization-actions=gs://dataproc-initialization-actions/jupyter.sh`, but you can also just copy that file into your own GCS bucket (e.g. `git clone <this-repo>`, modify `jupyter.sh`, `gsutil cp jupyter.sh gs://<YOUR_BUCKET/path`) and then create a cluster with `--initialization-actions=gs://YOUR_BUCKET/path`.

**Comment by jmwoloso** [comment]
@karth295 thank you for the clarification. so I actually was able to solve this in the following manner on our cluster:

**1. ssh into the cluster with port-forwarding (`-D 10000`):**
```
gcloud compute ssh "<your-cluster-here>"\
  --project "<your_project_here>" \
  --zone="us-west1-a" \
  -- -D 10000 -N -n &
```

**2. connect my browser to the cluster**
```
/usr/bin/google-chrome \
"http://<your_cluster_here>" \
--proxy-server="socks5://localhost:10000" \
--host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost" \
--user-data-dir=/tmp/
```
**3. ssh into the cluster from another terminal tab (with a remote shell):**
```
gcloud compute ssh "<your_cluster_here>"
```
**4. navigate to the desired directory and run:**
```jupyter notebook```

**5. at this point, the cluster won't be able to open a browser (because one doesn't exist) and it will give you a link to paste into a browser. paste the link into browser you connected to the cluster from step 2 above.**

**6. Alternative: after step 3, just install `nano` on the cluster and proceed to copy the script that you want to run from your local file system to the remote ssh terminal and save it on the cluster, then just use (from the remote ssh terminal command line):**
```
spark-submit <your_python_file>.py
```
