### ISSUE TITLE
tez-ui won't start using tez.sh as initialization script for dataproc

### ISSUE THREAD

**Issue by podwhitehawk** [GoogleCloudPlatform/dataproc-initialization-actions#165]
Hello, 

as described in subject, tez-ui won't start on dataproc if used as initialization script.
I've traced the issue down and the root cause was too old nodejs package (v.0.10.x) available in debian-jessie repos.
making changes to install nodejs v8 from official repo fixed the issue.
I've already prepared PR for this change, see #164.

**Comment by karth295** [comment]
Fixed by #164 thanks!
