### ISSUE TITLE
Installing Jupyter with "--metadata 'MINICONDA_VARIANT=2" breaks gsutil

### ISSUE THREAD

**Issue by spark2ignite** [GoogleCloudPlatform/dataproc-initialization-actions#174]
When installing Jupyter using initialisation action and specifying --metadata 'MINICONDA_VARIANT=2, it breaks Google's gsutil. Without "MINICONDA_VARIANT=2" everything works fine.

How to reproduce:
```
gcloud dataproc --region us-east1 clusters create jupytertest --subnet 'projects/operations-1266/regions/us-east1/subnetworks/xpn-us-east1-shared1' --no-address --image-version 1.2 --project research-cluster-186207 --initialization-actions 'gs://dataproc-initialization-actions/jupyter/jupyter.sh' --metadata 'MINICONDA_VARIANT=2'
```

Will result in this:
![image](https://user-images.githubusercontent.com/5726975/35646357-9facaea6-06d7-11e8-874e-043b30f6a54a.png)

**Comment by karth295** [comment]
Weird. If you just `pip install google-compute-engine` it's okay, so somehow gsutil's environment got destroyed when switching to conda.

As a temporary workaround, you can use an init action to run `/opt/conda/bin/pip install google-compute-engine`. (It's not in the root user's $PATH by default, so use the absolute path)

**Comment by karth295** [comment]
For posterity, folks who like Python 2 can use the `jupyter2` init action: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/jupyter2

**Comment by karth295** [comment]
The alternative fix is to `export CLOUDSDK_PYTHON=/usr/bin/python`
