### ISSUE TITLE
gcloud components update causes timeout during dataproc create

### ISSUE THREAD

**Issue by nehalecky** [GoogleCloudPlatform/dataproc-initialization-actions#19]
Hello!

Due to the default gcloud sdk version included in Dataproc cluster having a bug in python2 path resolution (see: https://code.google.com/p/google-cloud-sdk/issues/detail?id=355), I am targeting the following shell script as an initialization action to update gcloud components (which resolves the python2 pathing issue). It looks like this:

```bash
#!/usr/bin/env bash

# Update Google Cloud SDK
if [[ "${ROLE}" == 'Master' ]]; then
    gcloud components install alpha beta -q
fi
gcloud components update -q
exec -l $SHELL

```

Unfortunately, the Dataproc cluster errors on creation (logs attached below)
```bash
Waiting on operation [operations/projects/bombora-dev/operations/81b2e287-bcba-4d64-be7c-b253d19de47e].
Waiting for cluster creation operation...done.
ERROR: (gcloud.beta.dataproc.clusters.create) Operation [operations/projects/bombora-dev/operations/81b2e287-bcba-4d64-be7c-b253d19de47e] failed: Multiple Errors:
 - Google Cloud Dataproc Agent reports failure. If logs are available, they can be found in 'gs://dataproc-e66c6e3d-80da-4211-b66c-0109bbe4567a-us/google-cloud-dataproc-metainfo/04a941d2-8eff-4ab1-b2f0-3c6988c1fb85/spark-cluster-m'.
 - Google Cloud Dataproc Agent reports failure. If logs are available, they can be found in 'gs://dataproc-e66c6e3d-80da-4211-b66c-0109bbe4567a-us/google-cloud-dataproc-metainfo/04a941d2-8eff-4ab1-b2f0-3c6988c1fb85/spark-cluster-w-1'..
```

[google-cloud-dataproc-metainfo-04a941d2-8eff-4ab1-b2f0-3c6988c1fb85-spark-cluster-w-1-dataproc-startup-script_output.txt](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/files/69167/google-cloud-dataproc-metainfo-04a941d2-8eff-4ab1-b2f0-3c6988c1fb85-spark-cluster-w-1-dataproc-startup-script_output.txt)
[google-cloud-dataproc-metainfo-04a941d2-8eff-4ab1-b2f0-3c6988c1fb85-spark-cluster-m-dataproc-startup-script_output.txt](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/files/69168/google-cloud-dataproc-metainfo-04a941d2-8eff-4ab1-b2f0-3c6988c1fb85-spark-cluster-m-dataproc-startup-script_output.txt)

Any help greatly appreciated—thanks much. :)

**Comment by pmkc** [comment]
I believe it's actually the <code>exec -l $SHELL</code>, that is your issue. Initialization actions need to complete and exit 0, whereas that will just hang forever. If you remove that last line, it should work.

**Comment by nehalecky** [comment]
@pmkc, thanks for the tip! I will try it out soon, and let you know! In the meantime, do you have any timeline on when you will be updating the default version of gcloud sdk provided with dataproc? Thanks again. :)

**Comment by nehalecky** [comment]
@pmkc, thanks much—that resolved the issue. Closing.
