### ISSUE TITLE
Fix SparkR in Zeppelin init action

### ISSUE THREAD

**Issue by DariuszAniszewski** [GoogleCloudPlatform/dataproc-initialization-actions#198]
Per @pmkc suggestion in, #191 I removed configuration of SparkR - it was commented-out and unmaintained for quite some time and simply doesn't work in current form.

However it should work. Ideally it should be togglable by some metadata key.

**Comment by karth295** [comment]
The Zeppelin init action is effectively deprecated in favor of the ZEPPELIN optional component, so closing this issue. We are planning to improve SparkR support in Dataproc 1.5 in the next few months.
