### ISSUE TITLE
Apache Tez

### ISSUE THREAD

**Issue by Spark2Ignite** [GoogleCloudPlatform/dataproc-initialization-actions#20]
We are starting to use Apache Tez for complex directed-acyclic-graph of tasks for processing data and it would be great if we could install it with Initialization Actions.

**Comment by evilsoapbox** [comment]
Done and done. There's a [pull request](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/21) with a Tez init action. We've had a few people ask. :)
