### ISSUE TITLE
Initialization scripts should be consistent with Shell Style Guide

### ISSUE THREAD

**Issue by szewi** [GoogleCloudPlatform/dataproc-initialization-actions#200]
This task will be used for future PRs when checking for scripts consistency with Shell Style Guide. 

So far for each init script there was separate issue created. This issue will aggregate all releated PRs. 
Link to guide:

https://google.github.io/styleguide/shell.xml

**Comment by karth295** [comment]
Closing this issue for now, as we have fixed at least the highly used initialization actions.
