### ISSUE TITLE
"AttributeError: type object 'IOLoop' has no attribute 'initialized'" when trying to start cluster

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/dataproc-initialization-actions#214]
I get this error when starting a cluster:

`ERROR: (gcloud.dataproc.clusters.create) Operation [projects/packard-campbell-bcaine/regions/global/operations/9a1ce889-ddf4-4ef8-99ac-c7d8f1912725] failed: Initialization action timed out. Failed action 'gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790672', see output in: gs://packard-campbell-bcaine-dataproc-5253179067/google-cloud-dataproc-metainfo/6c482a93-777b-4f9f-b89c-20c31eeb8571/notebook-prod-m/dataproc-initialization-script-2_output.`

Here's the relevant part of the output file:
```
Creating Jupyter config...
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/opt/conda/lib/python2.7/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/opt/conda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

Here's the command I'm running:

`gcloud dataproc clusters create notebook-prod --project packard-campbell-bcaine --zone us-central1-f --master-machine-type n1-highmem-8 --master-boot-disk-size 500 --image-version 1.2 --bucket packard-campbell-bcaine-dataproc-5253179067 --scopes https://www.googleapis.com/auth/bigquery --initialization-actions gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790670,gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790671,gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790672,gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790673 --single-node --metadata shutdown-script="gsutil rm gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790670 gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790671 gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790672 gs://packard-campbell-bcaine-dataproc-5253179067/startup_script_notebook-prod52531790673 gs://packard-campbell-bcaine-dataproc-5253179067/jupyter.zip" --metadata install-jupyter-ext=true --metadata clean-notebook-bucket=pc-bcaine-clean-notebook --metadata MINICONDA_VARIANT=2 --metadata MINICONDA_VERSION=4.3.27 --metadata user-bucket=packard-campbell-bcaine-dataproc-5253179067 --service-account bcaine-prod@packard-campbell-bcaine.iam.gserviceaccount.com`

I think it may have something to do with jupyter bumping the tornado library to version 5.0: https://stackoverflow.com/questions/49141525/install-jupyter-notebook-on-miniconda. If this looks like a jupyter issue and not a dataproc issue, I'd be happy to file the issue.

**Comment by karth295** [comment]
Yup, seems like a Jupyter issue: https://github.com/jupyter/kernel_gateway/issues/281.

FWIW, running `gcloud dataproc clusters create kpal-jupyter --initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh --metadata MINICONDA_VARIANT=2` worked for me. How did you hit this error? (Wondering whether I should leave this open against our repo or not)

**Comment by bencaine1** [comment]
You can go ahead and close this issue. I don't remember how we fixed it. If anyone else runs into this issue, please comment on this bug and I'll go digging for it.
