### ISSUE TITLE
SSH tunnel error

### ISSUE THREAD

**Issue by tuanavu** [GoogleCloudPlatform/dataproc-initialization-actions#22]
I am following the tutorial to install Jupyter Notebook in Dataproc.
https://cloud.google.com/dataproc/tutorials/jupyter-notebook

This step give me an error:
```
gcloud compute ssh  --zone=<master-host-zone> \
  --ssh-flag="-D 1080" --ssh-flag="-N" --ssh-flag="-n" <master-host-name>
```

- Error:
```
ssh: unknown option "-D 1080"
ssh: unknown option "-n"
```

**Comment by evilsoapbox** [comment]
Hi @tuanvu216 

Sorry for the delayed response here. What OS are you using? I cannot replicate this error on OS X or Ubuntu. Also, you're using the Cloud SDK to SSH as well, right?

James

**Comment by tuanvu216** [comment]
Hi @evilsoapbox 

It is Windows 7. And yes, I am using the Cloud SDK to SSH. As you can see I am using the gcloud command to SSH.

Thanks,
Tuan

**Comment by ipostanogov** [comment]
The following command works fine @ Windows 7:
```
gcloud compute ssh --zone=<master-host-zone> \
  --ssh-flag="-D" --ssh-flag="1080" --ssh-flag="-N" <master-host-name>
```

**Comment by dennishuo** [comment]
Tested and updated document to reflect the split flags, thanks! https://cloud.google.com/dataproc/tutorials/jupyter-notebook#create_an_ssh_tunnel
