### ISSUE TITLE
cloud-sql-proxy doesn't initialize in HA-mode

### ISSUE THREAD

**Issue by szewi** [GoogleCloudPlatform/dataproc-initialization-actions#222]
[cloud-sql-proxy.sh](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/cloud-sql-proxy/cloud-sql-proxy.sh) only initialize on m-0 when running in HA.

Steps to reproduce:
1. Create cloud SQL database:
`gcloud sql instances create my-db --tier db-n1-standard-1 --activation-policy=ALWAYS`

2. Use this database when creating HA cluster:

``` 
gcloud dataproc clusters create sql-ha \
--initialization-actions gs://dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh \
--initialization-action-timeout 5m \
--num-workers 2 \
--num-masters 3 \
--worker-machine-type n1-standard-4 \
--master-machine-type n1-standard-4 \
--scopes sql-admin \ 
--properties hive:hive.metastore.warehouse.dir=${my_warehouse_bucket} \
--metadata "hive-metastore-instance=my-project:my-zone:my-db"
```

As a result in dataproc-initialization-script-0_output from m-1 and m2 we can see at the end:
``` 
+ [[ Master == \M\a\s\t\e\r ]]
+ ((  ENABLE_CLOUD_SQL_METASTORE  ))
+ systemctl stop hive-metastore
 Failed to stop hive-metastore.service: Unit hive-metastore.service not loaded. ```

**Comment by szewi** [comment]
Interesting: 
when image version is specified to older release **--image-version "1.2.0"** 
init-action-works.

**Comment by szewi** [comment]
Retested with newest image 1.2.27. Still doesn't work.

**Comment by karth295** [comment]
Ah, hive metastore currently only runs on `-m-0`, but that may change in the future. I think that line just needs to say something like `if hive-metastore is enabled; stop it` (though I'm not sure how that translates into systemd commands).
