### ISSUE TITLE
zeppelin.sh error

### ISSUE THREAD

**Issue by tuanvu216** [GoogleCloudPlatform/dataproc-initialization-actions#23]
Error in the initialization script zeppelin.sh

```
E: Failed to fetch http://security.debian.org/pool/updates/main/c/cups-filters/libcupsfilters1_1.0.61-5+deb8u2_amd64.deb  404  Not Found [IP: 150.203.164.38 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by evilsoapbox** [comment]
What Dataproc version were you using? Rather, did you specify `0.1` or did you specify (or default) to `0.2`?

**Comment by tuanvu216** [comment]
It is default. But not sure why this happen, but the initialization script works fine now.

**Comment by evilsoapbox** [comment]
This may have been one of a few things. I suspect it may have been rate limiting from a mirror which temporarily caused an issue. I cannot replicate it so I am going to mark this closed. If we see it again, I'll re-open it!
