### ISSUE TITLE
Jupyter does not work when accessed from Google Cloud Shell preview

### ISSUE THREAD

**Issue by DanSedov** [GoogleCloudPlatform/dataproc-initialization-actions#230]
WebShell in Developers Console uses a URL such as one below instead of http://cluster-name-m:8084.
https://8084-dot-3696626-dot-devshell.appspot.com/notebooks/...

@karth295 helped me look into this and we found this in log, which hints at potential cross-origin filtering:

> Blocking Cross Origin API request for /api/contents.  Origin: https://8084-dot-3696626-dot-devshell.appspot.com, Host: 127.0.0.1:8084

https://github.com/twosigma/beakerx/issues/1963#issuecomment-334721791 suggests to add: `c.NotebookApp.allow_origin = '*'` in config. However, now Jupyter is perpetually "connecting" to kernel.

**Comment by karth295** [comment]
After further investigation, Cloud Shell Preview does not support websockets, only http :(

So to support Jupyter through Cloud Shell preview, we would need to run `jupyter kernelgateway` with arguments for HTTP-only mode: https://github.com/jupyter/kernel_gateway/blob/master/docs/source/http-mode.md.

For posterity, the repro is to create a cluster with Jupyter on it:

```
gcloud dataproc clusters create my-cluster --initialization-actions=gs://dataproc-initialization-actions/jupyter/jupyter.sh
```

Then, open [Cloud Shell](https://cloud.google.com/shell/) in the Cloud Console, and run this command to set up static port forwarding from cloud shell port 8084 to the cluster on port 8123 (Jupyter UI port):

```
gcloud compute ssh my-cluster-m --   -4 -N -L 8084:dataproc-jupyter-m:8123
```

Finally, open Cloud Shell Preview on port 8084 to see the Jupyter UI. You will see 404 errors.

SSH into the cluster and add `c.NotebookApp.allow_origin='*'` to `/root/jupyter/jupyter_notebook_config.py` and restart the Jupyter server (`sudo systemctl restart jupyter-notebook`).

Finally, refresh the Jupyter UI. Now, you will see Jupyter trying to connect to the kernel (aka trying to create websocket connection), but that will fail.

I'm inclined to close this issue as `Won't Fix` unless there's strong demand for it.
