### ISSUE TITLE
 Error in parsing of JUPYTER_CONDA_PACKAGES metadata variable

### ISSUE THREAD

**Issue by donaldrauscher** [GoogleCloudPlatform/dataproc-initialization-actions#234]
Specific line: conda install "${JUPYTER_CONDA_PACKAGES//:/ }"
This renders as: conda install "pkg1 pkg2 pkg3"

Throws a PackageNotFoundError.  We can fix this by removing the quotes OR keeping ":" as delimiter between packages.

**Comment by karth295** [comment]
Ah, thanks for the issue. This was broken in #223 . Prior to that, this block correctly used either ':' or ' ' as the delimiter.
