### ISSUE TITLE
Support Hue 4+

### ISSUE THREAD

**Issue by madorb** [GoogleCloudPlatform/dataproc-initialization-actions#242]
Hue 3.11 was released in August 2016, 4.2 has just been released, would love to see this updated to support a more current version of hue (for instance, prior to 4.0 it doesn't seem possible to connect hue to presto due to jdbc driver classpath support not being fully flushed out).
 
I'm not sure how the .deb packages that init script relies on are built, but it looks like presently only 3.11 is available, is that intentional?

**Comment by pmkc** [comment]
The .deb packages are built using a fork of Apache Bigtop. Bigtop upstream added Hue 4.1 in https://issues.apache.org/jira/browse/BIGTOP-2952 4 months ago. Unless there are unforeseen build issues it should probably get pulled into our next Dataproc Image version (1.3).

If you don't want to wait for that, you probably want to install Hue yourself from a tarball, though that does take some effort. If you do go that route feel free to contribute your init action.
