### ISSUE TITLE
datalab initialization script does not support python3 kernel

### ISSUE THREAD

**Issue by pabloazurduy** [GoogleCloudPlatform/dataproc-initialization-actions#249]
the datalab initialization script `datalab.sh` creates independent python kernel environment (from the local env)  [dockfile script](https://github.com/googledatalab/datalab/blob/master/containers/base/Dockerfile). this creates a  conflict when you start a python3 kernel, even if you configure the spark vars the version of the datalab image will differ from the local machine python3 version, or the workers version with the master version (datalab python3 instance)

```
ENV PYSPARK_PYTHON='/usr/bin/python3'
ENV PYSPARK_DRIVER_PYTHON='python3'
readonly PYTHONPATH="/env/python3:$(find /usr/lib/spark/python/lib -name '*.zip' | paste -sd:)"
```
dataproc workers have the `python=3.4` version while the datalab kernel version is `python=3.5`. Its possible to use the datalab virtualenv python instance with spark , but the datalab instance is inside a docker directory, is this the way to proceded?, what if we need a different version of python, its there a way to define the kernels for datalab ?

its there a recommended way to deal with this?, we already reach an encoding error using `python2/pandas` 

thanks !!

**Comment by karth295** [comment]
So Datalab's python 3.5 comes from here: https://github.com/googledatalab/datalab/blob/06cf1d7dda8ea4c303b7ac22e9f1e5f50f60e280/containers/base/Dockerfile#L128. tl;dr they run `conda install python==3.5`

**Comment by karth295** [comment]
You either need to change Datalab's python by forking their docker image, or change the system python. I suggest `conda`, but `virtualenv` would work too.

The [conda init action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/conda) installs python 3.6 by default, but you can change that by adding `'CONDA_PACKAGES="python==3.5"'`.
