### ISSUE TITLE
Storing Custom Dataproc images for fast cluster provisioning 

### ISSUE THREAD

**Issue by spark2ignite** [GoogleCloudPlatform/dataproc-initialization-actions#26]
I am using a lot of open source software on top of my Dataproc clusters using Initialization Actions, things like Presto, Tez and some others. Today, my cluster provisioning time is about 20 minutes - the Dataproc itself is ready within 90 seconds and then all the rest of taken by installation of additional software.

It would be great if I could save my own Dataproc image and use it when I provision new clusters and then all my additional software will be already in the image and the provisioning time will be back ±90 seconds.

Unless this feature is available, it's challenging to use Dataproc for workloads when I want to create a cluster, run the job and delete the cluster.

**Comment by tartavull** [comment]
+1

**Comment by evilsoapbox** [comment]
This is a great suggestion and has been something which has been on our radar for awhile.

Would you mind also shooting a copy of this to [`dataproc-feedback@google.com`](mailto:dataproc-feedback@google.com)? That list has many customers on it and I'd like to see if anyone else also has a +1 (since many of them do not check out GitHub.) I am also happy to send it and attribute it as well if you'd prefer. 

Cheers!

**Comment by Spark2Ignite** [comment]
Sure, go ahead and send it yourself ;-) Thanks!

**Comment by evilsoapbox** [comment]
Will do!

**Comment by MarkDunne** [comment]
+1

Any updates on this issue?

**Comment by snafis** [comment]
+1

**Comment by jrussek** [comment]
@evilsoapbox did this get any traction?

**Comment by evilsoapbox** [comment]
Hi all, yes. We are still planning on this feature. No firm ETA but it's under active investigation.

**Comment by evilsoapbox** [comment]
Still under active investigation. This feature is very high on our feature list for 2018.

**Comment by astanway** [comment]
+1, subscribing for updates. Strongly desire this

**Comment by nehalecky** [comment]
Hi @evilsoapbox and all. Is this PR related to this issue https://github.com/GoogleCloudPlatform/cloud-dataproc/pull/44?

**Comment by evilsoapbox** [comment]
Yep. :)

**Comment by evilsoapbox** [comment]
Accidental send. Good news, this is a public (beta) feature. Please test it
out and provide feedback.

https://github.com/GoogleCloudPlatform/cloud-dataproc/tree/master/custom-images

**Comment by astanway** [comment]
Nice! Two questions: how do we use the image to build a cluster? The only option we have is to pick an image-version on the `gcloud` cli, but putting in the image name doesn't seem to work.

Also, it looks like the image will only last for a month - why is there an expiration date on it?

**Comment by takeon8** [comment]
@astanway 
Hi! you can use the new BETA flag "--image" in gcloud 190.0.0. 
```
gcloud beta dataproc clusters create <cluster_name> --image <your_custom_image_name>
```

**Comment by takeon8** [comment]
@astanway 
The custom image itself is saved into your GCE images. It will not be deleted in 30 days. However, you cannot create a new cluster with an custom image that is more than 30 days old. Any cluster created before the 30 day is not affected.

**Comment by astanway** [comment]
I see - thanks. Any chance we can fix this eventually? I’d love to be able to completely destroy the cluster when I’m not using it and then quickly bring it back up with the same image. However, it would be a chore to have to regenerate the same image every 30 days.

**Comment by romankor** [comment]
Should the `imageUrl` supposed to work when using workflows ? 
I see it in the documentation , but its not visible in the api explorer.

```
            "managedCluster": {
                "clusterName": "export",
                "config": {
                    "masterConfig": {
                        "machineTypeUri": type,
                        "imageUri": "dataproc-export-image"

                    }
```

When using `imageUri` nothing gets created , and i dont seem to find any error in any of the logs
