### ISSUE TITLE
Race condition in Zeppelin initialization script

### ISSUE THREAD

**Issue by felixcheung** [GoogleCloudPlatform/dataproc-initialization-actions#27]
There seems to be a race condition with the interpreter.json file

dataproc_initialization_script output:
```
+ /usr/lib/incubator-zeppelin/bin/zeppelin-daemon.sh start
Zeppelin start   OK 
+ /usr/lib/incubator-zeppelin/bin/zeppelin-daemon.sh stop
Zeppelin stop   OK 
+ sed -i 's/"spark.executor.memory": "512m",/"spark.executor.memory": "",/' /usr/lib/incubator-zeppelin/conf/interpreter.json
sed: can't read /usr/lib/incubator-zeppelin/conf/interpreter.json: No such file or directory
```

When SSH into the master node the conf/interpreter.json is there.

Proposed change is to sleep a bit between
`/usr/lib/incubator-zeppelin/bin/zeppelin-daemon.sh start`
and
`/usr/lib/incubator-zeppelin/bin/zeppelin-daemon.sh stop`

**Comment by evilsoapbox** [comment]
Hey @felixcheung 

Good catch. The request looks OK to pull; have you agreed to the CLA? Sorry - I know it's a small fix but we can't merge unless we make the Googlebot happy.

Thanks!

James
