### ISSUE TITLE
Oozie web interface seems to be disabled

### ISSUE THREAD

**Issue by karth295** [GoogleCloudPlatform/dataproc-initialization-actions#282]
This is the error I see when I visit `CLUSTERNAME-m:11000/oozie`, following the instructions in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/oozie#oozie-web-interface:

```
Oozie web console is disabled.

To enable Oozie web console install the Ext JS library.

Refer to Oozie Quick Start documentation for details.
```

**Comment by mik-laj** [comment]
I think, it has been fixed in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/495
