### ISSUE TITLE
zeppelin dependency break on Dataproc image version 1.3

### ISSUE THREAD

**Issue by agronaught** [GoogleCloudPlatform/dataproc-initialization-actions#289]
Accessing snappy compressed files (parquet, avro) results in an error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, dataproc-jball-w-0.c.viv-speed.internal, executor 2): java.lang.UnsatisfiedLinkError: org.xerial.snappy.SnappyNative.uncompressedLength(Ljava/nio/ByteBuffer;II)I
	at org.xerial.snappy.SnappyNative.uncompressedLength(Native Method)
	at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:565)

**Comment by pmkc** [comment]
This is an upstream issue in Spark [SPARK-24018](https://issues.apache.org/jira/browse/SPARK-24018), which we are working on fixing.

In the meantime a workaround is the initialization action of:

    rm -f /usr/lib/spark/jars/snappy*
    wget https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.2.6/snappy-java-1.1.2.6.jar \
       -P /usr/lib/spark/jars

I'll leave the issue open until it is fixed in Dataproc image version 1.3.

**Comment by agronaught** [comment]
I can confirm this works against dataproc version 1.3.1.

**Comment by karth295** [comment]
Seems to have been fixed last year: https://cloud.google.com/dataproc/docs/release-notes#august_24_2018
