### ISSUE TITLE
Stackdriver initialization hangs due to configuration change

### ISSUE THREAD

**Issue by samschlegel** [GoogleCloudPlatform/dataproc-initialization-actions#297]
As of today, the stackdriver initialization action is failing due to the installer asking for input due to a configuration conflict. Since it seems to be updating stackdriver-agent instead of installing like it used to, is this initialization action no longer required to setup stackdriver monitoring?

### Logs
```
==============================================================================
Starting installation of stackdriver-agent
==============================================================================

Installing agent for Debian or Ubuntu.
OK
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  python-netifaces python-psutil stackdriver-extractor
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpython2.7
Suggested packages:
  libpq5 libhiredis0.10 default-jre
The following NEW packages will be installed:
  libpython2.7
The following packages will be upgraded:
  stackdriver-agent
1 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 2,719 kB of archives.
After this operation, 2,011 kB of additional disk space will be used.
Get:1 http://packages.cloud.google.com/apt/ google-cloud-monitoring-jessie/main stackdriver-agent amd64 5.5.2-381.jessie [1,638 kB]
Get:2 http://deb.debian.org/debian/ jessie/main libpython2.7 amd64 2.7.9-2+deb8u1 [1,081 kB]
Fetched 2,719 kB in 0s (4,063 kB/s)
Selecting previously unselected package libpython2.7:amd64.
(Reading database ... 88509 files and directories currently installed.)
Preparing to unpack .../libpython2.7_2.7.9-2+deb8u1_amd64.deb ...
Unpacking libpython2.7:amd64 (2.7.9-2+deb8u1) ...
Preparing to unpack .../stackdriver-agent_5.5.2-381.jessie_amd64.deb ...
Unpacking stackdriver-agent (5.5.2-381.jessie) over (5.5.2-379.sdl.jessie) ...
Processing triggers for systemd (230-7~bpo8+2) ...
Setting up libpython2.7:amd64 (2.7.9-2+deb8u1) ...
Setting up stackdriver-agent (5.5.2-381.jessie) ...
Installing new version of config file /etc/collectd.conf ...

Configuration file '/etc/default/stackdriver-agent'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** stackdriver-agent (Y/I/N/O/D/Z) [default=N] ?
```

**Comment by karth295** [comment]
I deployed a cluster with `--image-version=1.2.0` and it already had an older `stackdriver-agent` pre-installed:

```
$ dpkg-query -l | grep stackdriver-agent
ii  stackdriver-agent                     5.5.2-364.jessie                 amd64        Stackdriver system metrics collection daemon
```

My guess is that the install script silently upgraded the package earlier, but now has changed so that it prompts you to choose.

I repro'd this issue both on the latest `1.2.x` image as well as `1.2.0`:

```
Configuration file '/etc/default/stackdriver-agent'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** stackdriver-agent (Y/I/N/O/D/Z) [default=N] ? 
```

**Comment by karth295** [comment]
Newer images of `1.0` and `1.1` have the stackdriver agent too. Ancient images in the 1.0 and 1.1 line (which have already been deprecated) don't have the stackdriver agent.

So indeed this init action is no longer needed and should be deprecated.

The advice in the README is useful, so I'll leave the README up until we transfer the advice to regular documentation, like https://cloud.google.com/dataproc/docs/guides/stackdriver-monitoring

**Comment by karth295** [comment]
Just to be clear on what's happening:

* The Stackdriver agent is not installed on base GCE VMs
* Most Dataproc images have the stackdriver agent installed via the older `stack-install.sh` script, but they explicitly have disabled the agent by default.
* As noted in [cluster properties](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties), you can enable the stackdriver agent by passing `--properties dataproc:dataproc.monitoring.stackdriver.enable` to `gcloud dataproc clusters create`.

Also note that we now include HDFS and YARN metrics on all clusters, regardless of whether you enable the stackdriver agent for custom metrics: https://cloud.google.com/dataproc/docs/guides/stackdriver-monitoring.

CC @jmikula for deciding the next steps.

**Comment by samschlegel** [comment]
Thanks @karth295 for digging into this, and to @zhanbo72 for the fix!

**Comment by karth295** [comment]
FYI I'm looking into switching to the new install script in the Dataproc image build. That will make this init action unnecessary.

**Comment by karth295** [comment]
The fix for using the new install script rolled out a couple weeks ago. I'm going to deprecate this init action and replace it with a README that suggests setting the property @zhanbo72 mentioned.
