### ISSUE TITLE
Bug in dataproc-initialization-actions/jupyter/ causes different version on master and worker

### ISSUE THREAD

**Issue by willbowditch** [GoogleCloudPlatform/dataproc-initialization-actions#300]
I'm getting the following error using a basic cluster initialised using the `dataproc-initialization-actions/jupyter/` scripts. 

> Exception: Python in worker has different version 3.6 than that in driver 3.7, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.

I've confirmed this is the case: on the master version is 3.7.0 and on workers its 3.6.5. 

I've tracked down the issue to this segment of code: 
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/dced28ebd3780307418789ac51bfe8303030cd9a/jupyter/jupyter.sh#L44-L52

`conda` defaults to upgrading python to 3.7.0 for installations of `jupyter` causing the different versions. 

I think wither the init script should prevent conda from installing the new python version, or perhaps upgrading the workers (I did this manually for now). I'm not familiar with conda (use pip instead), so unsure if there is a straightforward fix for this.

**Comment by karth295** [comment]
For posterity, `--no-update-dependencies` does not work in this case.

A third possible solution is to install jupyter on all nodes so that the python environment starts out consistent between master and workers.
