### ISSUE TITLE
Workers are not displayed in Ganglia

### ISSUE THREAD

**Issue by rodrigoWizeLine** [GoogleCloudPlatform/dataproc-initialization-actions#316]
Hi everyone!

I just create a new Cluster with Ganglia using the dataproc-initialization-actions

`gcloud dataproc clusters create ganglia-test \
--initialization-actions gs://dataproc-initialization-actions/ganglia/ganglia.sh`

Everything works great, but when I create the tunnel and access the web interface, only the master node it is monitored and not the workers, am I missing something?

![image](https://user-images.githubusercontent.com/40773686/43864247-c9ea2d06-9b24-11e8-8fdd-4a1ed5a48fb4.png)

![image](https://user-images.githubusercontent.com/40773686/43864346-0eda1034-9b25-11e8-8405-a878860662e1.png)

**Comment by rodrigoWizeLine** [comment]
I think something still missing, Now I Can see the nodes, but no data are transferred from the nodes to the master

![image](https://user-images.githubusercontent.com/40773686/44594657-77aebb00-a78c-11e8-8f9a-437306425899.png)

Only 1 CPU but three hosts
![image](https://user-images.githubusercontent.com/40773686/44594714-a3ca3c00-a78c-11e8-9fd8-03cf54bb6153.png)

**Comment by medb** [comment]
Fix described here:
https://stackoverflow.com/questions/33369043/ganglia-seeing-nodes-but-not-metrics

**Comment by medb** [comment]
And this one: https://adamo.wordpress.com/2015/05/27/gmond-occupying-100-of-the-cpu/
