### ISSUE TITLE
Bigtable init action fails with cluster version <=1.1

### ISSUE THREAD

**Issue by functicons** [GoogleCloudPlatform/dataproc-initialization-actions#328]
Error log:

+ install_shc
+ wget -q http://repo.hortonworks.com/content/groups/public/com/hortonworks/shc-core/1.1.1-2.1-s_2.11/shc-core-1.1.1-2.1-s_2.11.jar -O /usr/lib/spark/external/shc-core-1.1.1-2.1-s_2.11.jar
/usr/lib/spark/external/shc-core-1.1.1-2.1-s_2.11.jar: No such file or directory
+ err 'Unable to install shc.'

Seems /usr/lib/spark/external doesn't exist in <=1.1.

**Comment by szewi** [comment]
@functicons I've opened the PR for this. 
We are explicitly extending SPARK_DIST_CLASSPATH by /usr/lib/spark/external/shc-core.jar which is a symlink to donwloaded connector jar, so creating those missing directories on dataproc 1.1 and 1.0 should be fine.

**Comment by szewi** [comment]
@functicons BTW if you plan to run spark jobs on older clusters most probably we should install proper connectors versions on different dataproc images. Dataproc 1.0, for example, we are running Spark 1.6.2 and 2.10.5 and there is shc-core-1.1.1-1.6-s_2.10.jar, but this probably deserves separate issue. WDYT?
