### ISSUE TITLE
YARN Applications using docker container

### ISSUE THREAD

**Issue by lomluca** [GoogleCloudPlatform/dataproc-initialization-actions#339]
Hi,

I would like to know if is it possible to configure YARN in order to run Container inside Docker images (for example preparing an environment with this type of configuration: https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/DockerContainers.html)

Thanks!

**Comment by karth295** [comment]
Yup, you can set configuration values when creating a cluster with `--properties` ([docs](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties)).

You can also check out [Google Container Registry](https://cloud.google.com/container-registry/) as a convenient place to store docker images in a way that's accessible to the nodes in your cluster.

**Comment by lomluca** [comment]
Maybe my question was not so clear: I actually tried with '--properties' but it is impossible, because I need to configure 'container-executer.cfg', a file not in the exposed set. If I do it with an init-script, it doesn't work anyway because it is executed at the end and the NodeManagers fail during the startup.
