### ISSUE TITLE
GPU Based Datalab Docker Image?

### ISSUE THREAD

**Issue by dcompgriff** [GoogleCloudPlatform/dataproc-initialization-actions#358]
Hey, does anyone know if there is an analogous datalab initialization setup that uses the GPU based docker images and nvidia-docker for initialization scripts? I see that this script pulls a datalab docker image, and was wondering if there was a GPU based docker image for datalab? (I know datalab itself has a Beta version that allows you to connect a GPU to the instance directly. I also know that ML engine exist, but that is is also a pain to do iterative model development from a notebook with ML engine)

**Comment by karth295** [comment]
Looks like datalab does have a docker image with GPU libraries: https://github.com/googledatalab/datalab/blob/master/containers/base/Dockerfile.gpu. If you want to submit a PR to add an option to the existing init action, I'd be happy to accept it.

**Comment by karth295** [comment]
I'm going to close this issue for now, unless there's more interest.
