### ISSUE TITLE
cloud_sql_proxy init action fails when hive metastore is not enabled

### ISSUE THREAD

**Issue by eerlich** [GoogleCloudPlatform/dataproc-initialization-actions#364]
Hi! I'm running the cloud_sql_proxy init action with `enable-cloud-sql-hive-metastore":"false"`, specifying an additional instance instead. It looks like https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/356/commits broke the initialization action for this use case, as now it fails after a while of
```About to run 'nc -zv localhost 3306' with retries...
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 1 failed! Sleeping 1.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 2 failed! Sleeping 1.```

**Comment by mikaylakonst** [comment]
Thanks for the feedback! Could you:
1. Share the rest of the initialization action output
2. Share the exact gcloud invocation you used to create your cluster so we can try to reproduce the issue on our end
3. Share the startup script output for your cluster. This is located in GCS, specifically in gs://{staging bucket}/google-cloud-dataproc-metainfo/{cluster uuid}/{instance name}/dataproc-startup-script_output. (This is the same place the initialization action output goes)
4. If the cluster is still up, could you check if the cloud sql proxy is running?
Thanks!

**Comment by eerlich** [comment]
Hi,

1. ```Created symlink /etc/systemd/system/multi-user.target.wants/cloud-sql-proxy.service → /usr/lib/systemd/system/cloud-sql-proxy.service.
About to run 'nc -zv localhost 3306' with retries...
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 1 failed! Sleeping 1.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 2 failed! Sleeping 1.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 3 failed! Sleeping 2.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 4 failed! Sleeping 3.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 5 failed! Sleeping 5.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 6 failed! Sleeping 8.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 7 failed! Sleeping 13.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 8 failed! Sleeping 21.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 9 failed! Sleeping 34.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 10 failed! Sleeping 55.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 11 failed! Sleeping 89.
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused
'nc -zv localhost 3306' attempt 12 failed! Sleeping 144.
Final attempt of 'nc -zv localhost 3306'...
nc: connect to localhost port 3306 (tcp) failed: Connection refused
nc: connect to localhost port 3306 (tcp) failed: Connection refused```
2. I use Apache Airflow on Cloud Composer to start the cluster. I don't know exactly what gcloud call it maps to, but here are the parameters I pass:
```t_create = DataprocClusterCreateOperator(
        task_id='create',
        init_actions_uris=["gs://dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh"],
        cluster_name=cluster_name,
        project_id=gcp_project_id,
        service_account_scopes=['https://www.googleapis.com/auth/sqlservice.admin',
                                'https://www.googleapis.com/auth/cloud-platform'],
        zone=zone,
        metadata= {"enable-cloud-sql-hive-metastore":"false",
            "additional-cloud-sql-instances":cloudsql_instance_str},
        properties={"spark:spark.dynamicAllocation.enabled":"false", "capacity-scheduler:yarn.scheduler.capacity.root.default.ordering-policy":"fifo"},
        num_workers=4,
        dag=dag)```
3. Is it possible to send this privately somehow? I don't think there are any major secrets in it but I'd rather not share it here, just to be on the safe side
4. The cluster is not up, as it ends up in an ERROR state and I delete it automatically with airflow.

**Comment by mikaylakonst** [comment]
You can try merging this PR to see if it resolves your issue:
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/367
