### ISSUE TITLE
Kerberos: Authenticating as a principal in the remote realm not allowing to run Hadoop commands

### ISSUE THREAD

**Issue by krishnabigdata** [GoogleCloudPlatform/dataproc-initialization-actions#369]
Hi @memoryoflife , @cyxxy 

I am using the `secure.sh` scripts to Kerberos the cluster and enable cross-realm trust with AD server.  Authenticating as a principal in the local realm using root user allows to successfully run Hadoop commands but when I use principal in the remote realm, I can successfully authenticate but when I  execute `hadoop fs -ls ` I get the below errors.

**Details:**
My Windows AD is running on on-premises

```
DEBUG ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException:
GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Fail to create credential. 
(63) - No service creds)]
```
Can you please help me on this.

**Comment by cyxxy** [comment]
Did you set up the cross-realm shared-key in the AD server?
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/secure#enabling-cross-realm-trust-to-an-active-directory

**Comment by cyxxy** [comment]
Sorry for the late reply. Try set the encryption type on your AD domain controller:
`ksetup /SetEncTypeAttr <YOUR_ON_CLUSTER_REALM> AES256-CTS-HMAC-SHA1-96
`
