### ISSUE TITLE
dataproc-initialization-actions prometheus.sh no longer in GCS

### ISSUE THREAD

**Issue by JessieJingxuGao** [GoogleCloudPlatform/dataproc-initialization-actions#388]
Running 
```
gcloud dataproc clusters create <My_own_CLUSTER_NAME> \
    --initialization-actions gs://dataproc-initialization-actions/prometheus/prometheus.sh
```
as documented in
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/prometheus

gave me the following error:
ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Google Cloud Storage object does not exist 'gs://dataproc-initialization-actions/prometheus/prometheus.sh'.

@karth295
@szewi 

I will try downloading and uploading the .sh file on Github to my GCP project GCS and call from there manually if the .sh file is not outdated

**Comment by karth295** [comment]
Thanks for the issue -- looks like the github repo and the GCS got out of sync. I've manually synced them again, so the Prometheus init action works now!
