### ISSUE TITLE
Pre-installed Tez on Dataproc 1.3 is failing when example job is submitted.

### ISSUE THREAD

**Issue by szewi** [GoogleCloudPlatform/dataproc-initialization-actions#392]
Steps to reproduce:
1. Create dataproc 1.3 cluster: 
`gcloud dataproc clusters create tez --image-version 1.3 `
2. Ssh into master node:
`gcloud compute ssh tez-m`
3. Run example Tez job:
`hadoop jar /usr/lib/tez/tez-examples.jar orderedwordcount file:///usr/lib/tez/LICENSE-MIT /tmp/tez-out`

Output: 

> java.lang.NoClassDefFoundError: org/apache/tez/dag/api/TezConfiguration
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> 	at java.lang.Class.getMethod0(Class.java:3018)
> 	at java.lang.Class.getMethod(Class.java:1784)
> 	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.<init>(ProgramDriver.java:59)
> 	at org.apache.hadoop.util.ProgramDriver.addClass(ProgramDriver.java:103)
> 	at org.apache.tez.examples.ExampleDriver.main(ExampleDriver.java:47)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
> 	at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
> Caused by: java.lang.ClassNotFoundException: org.apache.tez.dag.api.TezConfiguration
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 14 more

**Comment by szewi** [comment]
From Tez init action readme:
```Note that Tez is pre-installed on Dataproc 1.3+ clusters, so you should not run this initialization action on 1.3+ clusters.```. I assume there should be at least some info how to run tez jobs on pre-installed tez. Adding cluster property when creating dataproc cluster in version 1.3 is sufficient to fix this issue:
`--properties 'hadoop-env:HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:/etc/tez/conf:/usr/lib/tez/*:/usr/lib/tez/lib/*'`

**Comment by functicons** [comment]
Thanks for catching this! Could you make a CL to the Tez init action README to clarify "--properties ..." is needed to enable Tez for 1.3+ clusters?

**Comment by szewi** [comment]
@functicons Sure! I submitted a PR with that info. Could you take a look?

**Comment by functicons** [comment]
@szewi Can you submit the PR?

**Comment by szewi** [comment]
Hi @functicons the PR is here https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/394 already approved and waiting to be merged.
