### ISSUE TITLE
Dataproc RStudio Initialization Action Fails

### ISSUE THREAD

**Issue by nsteblay** [GoogleCloudPlatform/dataproc-initialization-actions#397]
I'm getting the following error when using the R Studio initialization action for Dataproc.

+ apt-key adv --keyserver keys.gnupg.net --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.airKXC3vNe/gpg.1.sh --keyserver keys.gnupg.net --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
gpg: keyserver receive failed: No data

If I run from the cloud shell I get ...

Executing: /tmp/apt-key-gpghome.M5CyBeuCHQ/gpg.1.sh --keyserver keys.gnupg.net --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
key AD5F960A256A04AF:
4 signatures not checked due to missing keys
gpg: key AD5F960A256A04AF: public key "Johannes Ranke (Wissenschaftlicher Berater) <johannes.ranke@jrwb.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1
key AD5F960A256A04AF:
4 signatures not checked due to missing keys
gpg: no writable keyring found: Not found
gpg: error reading '[stdin]': General error
gpg: import from '[stdin]' failed: General error
gpg: Total number processed: 0

**Comment by functicons** [comment]
This is caused by the Debian issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913614. A workaround is adding `--no-tty` to `apt-key adv`. I'll make a PR to fix the init action.

**Comment by rodrigo1406** [comment]
apt-key adv --keyserver --no-tty keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'

gpg: Note: '--recv-key' is not considered an option
gpg: WARNING: no command supplied.  Trying to guess what you mean ...

**Comment by medb** [comment]
@rodrigo1406 please, file a new issue with detailed description of the failure and steps to reproduce it.
