### ISSUE TITLE
Would be great to have Presto Initialization Action Example

### ISSUE THREAD

**Issue by Spark2Ignite** [GoogleCloudPlatform/dataproc-initialization-actions#4]
https://prestodb.io

**Comment by evilsoapbox** [comment]
Agreed.

We'll (probably) need to deploy some fixes to get Presto working well; this is a great idea.

**Comment by evilsoapbox** [comment]
Hello @Spark2Ignite - we just pushed a sample initialization action to install Presto (https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/presto/)

Happy querying!

**Comment by Spark2Ignite** [comment]
Awesome! I am going to test it tomorrow and will provide feedback

**Comment by Spark2Ignite** [comment]
I have tried to deploy Presto IA on couple of clusters. Everything works nicely!
