### ISSUE TITLE
Host publicly available copy of init-actions on GCS.

### ISSUE THREAD

**Issue by nehalecky** [GoogleCloudPlatform/dataproc-initialization-actions#40]
Hi All,

As a service to existing Dataproc users and potential adopters, any way we could get a copy of this repo's master branch hosted on publicly available google cloud bucket (e.g., `gs://dataproc-initalizations-actions`)? I believe this would help much in allowing users to quickly reference and leverage init-action functionality in a `gcloud dataproc cluster create` call, along with having a public resource for testing against (until the Dataproc team is able to provide some sort of testing and CI service). 

Thanks!

**Comment by evilsoapbox** [comment]
Very reasonable request - I will do this tonight!

**Comment by evilsoapbox** [comment]
The bucket `gs://dataproc-initialization-actions` now has a copy of this repository (sans some of the fluff, like the favico) ready to go. In the future, I'll do a better job of keeping it up to date. :)

James

**Comment by nehalecky** [comment]
@evilsoapbox, thanks much!
