### ISSUE TITLE
Expose Hadoop metrics in Ganglia

### ISSUE THREAD

**Issue by medb** [GoogleCloudPlatform/dataproc-initialization-actions#412]
Currently Ganglia shows only VM metrics, but we need expose at least Hadoop metrics as well.

**Comment by medb** [comment]
@adam-stasiak May you work on this issue?

**Comment by karth295** [comment]
Since very few people use Ganglia (afaik), I'm going to close this issue for now. Stackdriver is generally a better solution, because metrics persist even after a cluster is deleted.
