### ISSUE TITLE
Latest changes to Conda init action break customers

### ISSUE THREAD

**Issue by medb** [GoogleCloudPlatform/dataproc-initialization-actions#424]
Breaking commits:
- https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/065c968d5615db6cb95d380924a703b7cb8ce70a
- https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/6d5cc27b92c15ad11c51814681bed09d0266bdda

To mitigate this issue, above commits were rolled back in init actions GCS bucket.

**Comment by Nhlakaniphofx** [comment]
Issue still persisting:
Trying to initialize jupyter with when creating a  dataproc using the arg: 
--initialization-actions \
            gs://dataproc-initialization-actions/jupyter/jupyter.sh

The dataproc creation fails and when I check the logs I get:
 source /etc/profile.d/conda.sh
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 31: /etc/profile.d/conda.sh: No such file or directory

When I remove the jupyter initialization argument I get no issues and dataproc starts up as normal. Hence leading me to assume something was changed on the file gs://dataproc-initialization-actions/jupyter/jupyter.sh

Please advise on fix or if there is any work around on this issue?

**Comment by Joel92** [comment]
I am experiencing the same problem as @Nhlakaniphofx . However, I have tested with the previous version of gs://dataproc-initialization-actions/jupyter/jupyter.sh and **still fails**, same error. The only way to run Jupyter Notebooks on Dataproc now is with our custom image.

**Comment by MaxAVF** [comment]
Same error, try changing `source /etc/profile.d/conda.sh
if [[ -f /etc/profile.d/conda.sh ]]; then
  source /etc/profile.d/conda.sh
fi

if [[ -f /etc/profile.d/effective-python.sh ]]; then
  source /etc/profile.d/effective-python.sh
fi` 

for ' source /etc/profile.d/effective-python.sh' 

And seems to work

**Comment by medb** [comment]
Thanks for information, updated Jupiter init action to latest version in GCS bucket.

**Comment by functicons** [comment]
Thanks for the bug report! Thank Igor for dealing with the issue.

In https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/6d5cc27b92c15ad11c51814681bed09d0266bdda, I accidentally removed the executable permission of conda/bootstrap-conda.sh and conda/install-conda-env.sh, which breaks jupyter/juypter.sh which relies on conda/bootstrap-conda.sh to be executable.

I realized this in my local Jupyter test, so my https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/065c968d5615db6cb95d380924a703b7cb8ce70a was intended to fix that.

**Comment by functicons** [comment]
I re-uploaded conda scripts from HEAD https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/ae949d1a4c03912ddef79357ed428523144f47b3 to the GCS bucket. Jupyter is already the latest.

Please use the latest conda and jupyter scripts together. Let me know if there is any issue.
