### ISSUE TITLE
R-Studio Initialization Fails

### ISSUE THREAD

**Issue by nsteblay** [GoogleCloudPlatform/dataproc-initialization-actions#426]
After creating a Dataproc cluster with the rstudio initialization action I get the following errors from ldd ...

ldd /usr/lib/rstudio-server/bin/rserver

	linux-vdso.so.1 (0x00007fff3ec58000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6621d53000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6621b36000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f6621933000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f662172e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6621526000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f662130c000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6620f8a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6620c86000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6620a6f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f66206d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6621f57000)

It appears that libssl.so.1.0.0 and libcrypto.so.1.0.0 are not installed.

Installed ...

openssl version
OpenSSL 1.0.2p  14 Aug 2018

**Comment by PuskasDuck** [comment]
+1 on getting a fix for this. Tried on latest dataproc preview too, same error.
