### ISSUE TITLE
Remove "beta" from gcloud commands

### ISSUE THREAD

**Issue by Dnefedkin** [GoogleCloudPlatform/dataproc-initialization-actions#43]
As Dataproc is in GA, it make sense to replace "gcloud beta dataproc" to "gcloud dataproc" in all the README files.

**Comment by evilsoapbox** [comment]
Good call, picking this up now.

**Comment by evilsoapbox** [comment]
All fixed. Thanks for mentioning this! If you see any other beta references, please let me know.
