### ISSUE TITLE
New toree setup breaks jupyter setup

### ISSUE THREAD

**Issue by czarstark** [GoogleCloudPlatform/dataproc-initialization-actions#438]
The following error occurs due to a malformed URL:

`+ ./dataproc-initialization-actions/jupyter/internal/setup-jupyter-kernel.sh
Creating Jupyter config...
Writing default config to: /root/.jupyter/jupyter_notebook_config.py
Installing pyspark Kernel...
Determined SPARK_MAJOR_VERSION to be '2'
Found PY4J_ZIP: '/usr/lib/spark/python/lib/py4j-0.10.7-src.zip'
[InstallKernelSpec] Installed kernelspec pyspark in /usr/local/share/jupyter/kernels/pyspark
Collecting https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz
  HTTP error 404 while getting https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz
  Could not install requirement https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz because of error 404 Client Error: Not Found for url: https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz
Could not install requirement https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz for URL https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz`

I will be correcting this URL and submitting a pull request shortly.

**Comment by czarstark** [comment]
#439 corrects this issue.

**Comment by medb** [comment]
Thanks for fix.
