### ISSUE TITLE
Support Kafka 2.0

### ISSUE THREAD

**Issue by skjagini** [GoogleCloudPlatform/dataproc-initialization-actions#443]
Kafka 2.0 was released recently and would love to see init action updated to the latest stable, we are currently using Kafka version which doesn't have proper support for Kafka Connect, Kafka Streams (or KSQL) etc. 

I'm not sure how the packages that init script relies on are built, but it looks like presently the supported Kafka version is way behind.

**Comment by functicons** [comment]
We are upgrading Kafka to 1.1.1 in Dataproc 1.4 preview. It will be available soon. There is no ETA for Kafka 2.0 yet.

**Comment by skjagini** [comment]
Great that should do it. Will check out 1.4 once it is available.

**Comment by functicons** [comment]
Components installed from init actions are currently not documented. We will improve that, thanks for pointing this out!

**Comment by medb** [comment]
Supported in Dataproc 1.5 that is in preview now.
