### ISSUE TITLE
Support for NVIDIA CUDA 9.0 

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/dataproc-initialization-actions#461]
TensorFlow pipy package has been compiled using CUDA 9.0/CuDNN, current GPU dataproc initialization instructions support CUDA 9.1 which is not compatible, hence is not possible to run TensorFlow (pip install tensorflow-gpu) Latest GA 1.12
New TensorFlow 1.13rc2 and 2.0 preview support CUDA 10/CuDNN.

**Comment by karth295** [comment]
Tensorflow 1.13 is GA now, so closing this issue.
