### ISSUE TITLE
GCS and Git out of sync

### ISSUE THREAD

**Issue by JessieJingxuGao** [GoogleCloudPlatform/dataproc-initialization-actions#475]
Hi there,

Looks like the initialization scripts for both of the jupyter versions are no longer in the designated GCS bucket. 
-bash: ,gs://dataproc-initialization-actions/jupyter2/jupyter2.sh: No such file or directory
-bash: ,gs://dataproc-initialization-actions/jupyter/jupyter.sh: No such file or directory

I am calling from my GCS bucket right now.

**Comment by medb** [comment]
It's there:
```bash
$ gsutil ls -al gs://dataproc-initialization-actions/jupyter2/jupyter2.sh
      3351  2019-01-24T19:28:18Z  gs://dataproc-initialization-actions/jupyter2/jupyter2.sh#1548358098868635  metageneration=1
```

What are you trying to do? Are you using init action during cluster creation? May you share it and cluster creation command?

**Comment by JessieJingxuGao** [comment]
Just got time to check it. Yea it's working now... Please close this ticket.

Maybe it was just me having an extra space before the second init action path?

I was using init action during dataproc cluster creation, something like the below.
gcloud dataproc clusters create dummy-name --region us-east1 --subnet <dummy_net> --zone=us-east1-b --single-node --master-machine-type n1-stan
dard-1 --master-boot-disk-size 500 --image-version 1.3-deb9 --scopes=https://www.googleapis.com/auth/cloud-platform --tags=dummy-tag --project=<project_name> --initialization-action
s=gs://dataproc-initialization-actions/hue/hue.sh,gs://dataproc-initialization-actions/jupyter2/jupyter2.sh
