### ISSUE TITLE
Specify several initialization actions during cluster create

### ISSUE THREAD

**Issue by yamabt** [GoogleCloudPlatform/dataproc-initialization-actions#477]
I am trying to create a dataproc cluster with Jupyter installed on it.
Thus using the --initialization-actions flag and google storage uri.

Is is possible to specify several URIs such as:

```
--initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh, gs://cluster-init/install-packages.sh
```

I am getting an error when I try to do this.
I have tried specifying additional URIs separated with comma, space, and comma separated within an array ( [URI1, URI2]  ). Not working.

I will attach my file and the output from cloud shell.

Thank you! Perhaps this is a trivial question for many of you but I'm no expert in this field.

[dataproc-init.txt](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/files/2946748/dataproc-init.txt)

![2019_03_08_17_51_21_cloud_shell_bmb_analytics_google_cloud_platform](https://user-images.githubusercontent.com/40788775/54042779-4303cd80-41cb-11e9-865a-e2e0b057ba07.png)

**Comment by medb** [comment]
You should not have spaces between init actions, just commas:
```
--initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh,gs://cluster-init/install-packages.sh
```
