### ISSUE TITLE
Adding support for Presto 307 

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#492]
Current Dataproc init action is using an old version of Presto: 
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/9a0f885697358b454e9b5dd21cf709b23f4181fb/presto/presto.sh#L30

Even on it's linked with old [repo](https://repo1.maven.org/maven2/com/facebook/presto)
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/9a0f885697358b454e9b5dd21cf709b23f4181fb/presto/presto.sh#L58

Latest Repo of Presto is https://repo1.maven.org/maven2/io/prestosql/presto-server/307/presto-server-307.tar.gz

Please update to 307 ÅSAP.

Thanks, will be waiting for the update :)

**Comment by medb** [comment]
Starbust Presto added in #528 and updated in #590
