### ISSUE TITLE
Presto is not supporting administering and even cli not working..

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#494]
Presto is not supporting administering [http://presto-cluster-m:8080]
 and 
channel 13: open failed: administratively prohibited: open failed
channel 14: open failed: administratively prohibited: open failed
channel 14: open failed: connect failed: Connection refused

and When I try to connect to CLI using:
```
gcloud compute ssh presto-cluster-m \
    --project=${PROJECT} \
    --zone=${ZONE} \
    -- -D 1080 -N
``` 
and 
```
./presto-cli \
    --server presto-cluster-m:8080 \
    --socks-proxy localhost:1080 \
    --catalog hive \
    --schema default
```

It gives this error: "**Error running the command: java.net.SocketException: Malformed reply from SOCKS server**"

**Comment by medb** [comment]
If you are using Dataproc 1.3+, you may want to use Dataproc Presto [Component](https://cloud.google.com/dataproc/docs/concepts/components/overview) instead:
```bash
gcloud dataproc clusters create ${CLUSTER_NAME} --optional-components=PRESTO
```

**Comment by ChethanUK** [comment]
Which version of PrestoSQL does that use?

**Comment by medb** [comment]
I uses Presto 0.215

All versions are documented here:
https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.3

**Comment by ChethanUK** [comment]
Hey, It would be nice if you update to latest presto version
Check:
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/493

**Comment by ChethanUK** [comment]
> ```shell
> ```shell
> gcloud dataproc clusters create ${CLUSTER_NAME} --optional-components=PRESTO
> ```
> ```

So Full command will be :
```
gcloud dataproc clusters create presto-test --optional-components=PRESTO
--zone europe-west1-b \
      --master-machine-type n1-standard-4 \
      --master-boot-disk-size 1000 \
      --num-workers 2 \
      --num-preemptible-workers 4 \
      --worker-machine-type n1-standard-4 \
      --worker-boot-disk-size 1000 \
      --scopes 'https://www.googleapis.com/auth/cloud-platform' \
      --project ${PROJECT} \
      --initialization-actions 'gs://${BUCKET}/presto/presto.sh' ``` Right ?

**Comment by medb** [comment]
No, if you use `PRESTO` component, you don't need to use `gs://${BUCKET}/presto/presto.sh` Presto initialization action.

**Comment by ChethanUK** [comment]
Okay, What about #493 ?

And What about Presto Admin? or is there any alternatives so that I can copy catalog.properties to all the worker's nodes.?

**Comment by ChethanUK** [comment]
> use `PRESTO` component,

Okay, I used presto component but still 

When I ran these: 
`
gcloud compute ssh presto-cluster-m --project=${PROJECT} --zone=${ZONE} -- -D 1080 -N
`
and 
`
./presto-cli-0.218 --server presto-clusters-m:8080 --socks-proxy localhost:1080
`

I got same error:
```
**Error running command: java.net.SocketException: Malformed reply from SOCKS server**

**channel 2: open failed: connect failed: Connection refused**
```

**Comment by medb** [comment]
For Presto Component you need to use 8060 port instead of 8080:
```
./presto-cli-0.218 --server presto-clusters-m:8060 --socks-proxy localhost:1080
```

**Comment by ChethanUK** [comment]
Yeah, I tried that also

```
./presto-cli-0.218     --server presto-test-m:8060     --socks-proxy localhost:1060 
presto> show catalogs;
Error running command: java.net.SocketException: Malformed reply from SOCKS server
```

and 
```
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
```

**Comment by functicons** [comment]
I couldn't reproduce the problem, it worked for me:

1) Create a Presto cluster.

$ gcloud beta dataproc clusters create presto-cluster --optional-components=PRESTO --image-version=1.3

2) Create SSH tunnel.

gcloud compute ssh presto-cluster-m --zone=<zone> -- -D 1080

3) Connect to the Presto server.

$ ./presto-cli --server presto-cluster-m:8060 --socks-proxy localhost:1080 --catalog hive --schema default

presto:default> show tables;
 Table 
-------
(0 rows)

Query 20190409_165435_00005_tcjez, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

**Comment by ChethanUK** [comment]
--image-version=1.3

I was using 

```
--image-version 1.4-debian9 \      
--optional-components=PRESTO \
```

**Comment by ChethanUK** [comment]
@functicons @medb Need support for PrestoSQL. Right now, Only PrestoDB component is available, it would be nice to have PrestoSQL as well..

**Comment by functicons** [comment]
@ChethanUK Please separate different issues, for this issue just focus on the "Presto is not supporting administering and even cli not working". Can you still reproduce it by following my steps?

**Comment by ChethanUK** [comment]
> gcloud compute ssh presto-cluster-m --zone= -- -D 1080

This command is invalid...

So, I used `gcloud compute ssh presto-cluster-1-m --zone=${ZONE_NAME} -- -D 1080 -N`

and then I got same error
`./presto-cli-0.218 --server presto-cluster-m:8060 --socks-proxy localhost:1080`
presto> show catalogs;
```Error running command: java.net.SocketException: Malformed reply from SOCKS server```

**Comment by medb** [comment]
You need to use CLI for Presto `0.215` (version that installed on Dataproc), not `0.218`

**Comment by ChethanUK** [comment]
> not `0.218`

That was the not issue though, Anyway I got it fixed thanks!.
