### ISSUE TITLE
Requesting tutorials on Beam on Dataproc

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#499]
Hey @medb ,

If possible, can you give a tutorial on [Beam](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/beam/beam.sh) on dataproc

is it just:
```
gcloud dataproc clusters create beam-flink \
      --zone europe-west1-b \
      --master-machine-type n1-standard-4 \
      --master-boot-disk-size 1000 \
      --num-workers 2 \
      --num-preemptible-workers 4 \
      --worker-machine-type n1-standard-4 \
      --worker-boot-disk-size 1000 \
      --image-version 1.4-debian9 
      --initialization-actions \
            gs://dataproc-initialization-actions/beam/beam.sh
 ```

Will it manage Both Spark and Flink runner for Beam?

**Comment by bsidhom** [comment]
It depends on whether you want to use the original Java API or the portable runner (e.g., for running Go or Python pipelines).

Using the Java API is easiest:

* Package your pipeline into an uber-jar (e.g., using [maven shade](https://maven.apache.org/plugins/maven-shade-plugin/usage.html) or [gradle shadow](https://imperceptiblethoughts.com/shadow/introduction/)). 
  * Make sure to [merge service files](https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files) so they can be resolved by the Beam SDK.
  * The [Beam website](https://beam.apache.org/documentation/runners/spark/) has an example of this.
* Submit the uber-jar to Dataproc using the _Spark_ runner:
```bash
gcloud dataproc jobs submit spark \
  --cluster my-cluster \
  --zone europe-west1-b \
  --jar uberjar.jar \
 -- \
  --runner=SparkRunner \
  <additional job args>
```

You can then monitor job progress as usual using the Spark YARN UIs.

Submitting jobs via the portability API is more complex. You're also shooting at a moving target, so I will give a rough overview here:
* Start a Dataproc cluster with the Docker init action and Flink init action, _without_ a detached Flink session.
  * The Flink init action is [documented here](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/flink). 
  * The Docker init action is [documented here](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/docker).
  * Make sure to set `--metadata START_FLINK_YARN_SESSION_DEFAULT=false` or the default detached session will consume all cluster resources.
* SSH into the master node and set up the portable Flink job server:
  * Check out the Beam source repository [at the appropriate version tag](https://beam.apache.org/documentation/runners/flink/#version-compatibility). The required version will vary based on the SDK version you're targeting. Please file a feature request if we do not support a Flink version you need.
  * Build the portable Flink job server uber-jar, e.g.: `./gradlew :beam-runners-flink_2.11-job-server:shadowJar` (Note that this mechanism may have changed if Flink has moved to a Docker-based job server deployment.)
  * Execute the shadow jar against YARN:
```bash
flink run \
  -m yarn-cluster \
  -yn N \
  -ynm <job manager memory (MB)> \
  -ytm <task manager memory (MB)> \
  <job server jar>
```
* Finally, package up your pipeline and submit it using the SDK. How you do so will depend on which SDK you're using. For example:
  * If you're using Java:
    * Package your pipeline into an uber-jar:
      * Your pipeline code now lives separately from the runner and should _not_ depend on or package the Spark _or_ Flink runner. Depend on core Beam SDKs as usual.
      * Add a dependency on the PortableRunner. This should live under the [beam-runners-reference-java](https://search.maven.org/artifact/org.apache.beam/beam-runners-reference-java/2.11.0/jar) artifact.
    * Finally, execute your main class against the PortableRunner. Make sure to specify the Flink portable runner endpoint here--at the time of this writing it defaults to localhost:8099:
```bash
java -cp uber.jar your.package.Main \
  --runner=PortableRunner \
  --job_endpoint=localhost:8099 \
  <additional job args>
```
  * If you're using Python:
    * Execute your pipeline script, specifying the runner location:
```bash
<main entrypoint> \
  --runner=PortableRunner \
  --job_endpoint=localhost:8099 \
  <additional job args>
```

There's one additional caveat for running portable pipelines at this time: Beam [does not yet](https://issues.apache.org/jira/browse/BEAM-4117) publish [SDK container images](https://beam.apache.org/contribute/docker-images/). You'll need to build these images (e.g., as referenced for [Python wordcount](https://beam.apache.org/roadmap/portability/#python-on-flink) or [Java wordcount](https://beam.apache.org/documentation/runners/flink/#executing-a-beam-pipeline-on-a-flink-cluster)) and ensure that they're available on the Dataproc cluster. You can either do so by retagging and pushing those images to a _public_ repository or by uploading them to your own gcr.io and running a custom init action that [authenticates each node to use GCR](https://cloud.google.com/container-registry/docs/quickstart#add_the_image_to).
