### ISSUE TITLE
hue initialization failed for apt-get update 

### ISSUE THREAD

**Issue by suibinz** [GoogleCloudPlatform/dataproc-initialization-actions#505]
This occurs for 1.3 or 1.1 image versions (1.2  presumed).

The package data repo in `http://storage.googleapis.com/dataproc-bigtop-repo` seems to only contain 1.1. Furthermore, regardless 1.3 or 1.1, it does not look like the `1."x"_deb8_20190312_015100-RC01` exits.

Script trace:
```
...
Hit:12 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Err:13 http://storage.googleapis.com/dataproc-bigtop-repo/1_1_deb8_20190312_015100-RC01 dataproc Release
  403  Forbidden
Reading package lists...
E: The repository 'http://storage.googleapis.com/dataproc-bigtop-repo/1_1_deb8_20190312_015100-RC01 dataproc Release' does no longer have a Release file.
```

**Comment by functicons** [comment]
Dataproc 1.3 and 1.1 both worked for me:

    gcloud dataproc clusters create my-cluster --image-version=1.3 --initialization-actions gs://dataproc-initialization-actions/hue/hue.sh
