### ISSUE TITLE
Not able to save file nor rename files in Jupyter Notebook gateway

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#509]
I installed Dataproc with a simple command:
```
gcloud beta dataproc clusters create presto \
--optional-components=ANACONDA,JUPYTER,PRESTO \
--zone europe-west3-a --master-machine-type n1-standard-2 --master-boot-disk-size 500 \
--num-workers 2 --worker-machine-type n1-standard-2 --worker-boot-disk-size 500 \
--num-preemptible-workers 1 \
--image-version 1.4-debian9 \
--enable-component-gateway
```
Once, Dataproc is installed opened Jupyter notebook gateway and tried creating a new notebook and tried renaming it, but I got error:
![Rename error](https://i.imgur.com/TtgScIO.png)

Then, tried creating new Folder it also gave an error:
![Error creating folder](https://i.imgur.com/xuv1MMi.png)

Initializing and creating the cluster is just scripts right, why it's behaving differently every damm time?

A lot of problems:
[Stuck at interpreter initializing](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/507)
Unable to save the code, just closing the notebook window will delete [Not saving the code]
Lack of documentation, For example, how can a user import library dependency lets say 'spark-cassandra-connector:2.4.1-s_2.11'. In python, it's very easy just `!pip install package` and [docs](https://cloud.google.com/datalab/docs/how-to/adding-libraries) of python jupyter notebook was good but dataproc is ...

**Comment by karth295** [comment]
This is an issue with Component Gateway that we're working on fixing in the next couple weeks. I believe the underlying cause is that our deployment of Knox doesn't allow PATCH requests by default.

Renaming jupyter notebooks still works if you use the old ssh tunnel method (edit and run launch-jupyter-interface.sh).

**Comment by karth295** [comment]
Seems to have been fixed over a month ago: https://cloud.google.com/dataproc/docs/release-notes#may_6_2019
