### ISSUE TITLE
Pyspark Jupyter kernel configuration json overrides PYTHONPATH

### ISSUE THREAD

**Issue by guilhermelaranja** [GoogleCloudPlatform/dataproc-initialization-actions#519]
Starting with some context, I'm using Dataproc to run Jupyter Notebooks with Spark and Hadoop.

I really want to add something to my PYTHONPATH on the Jupyter Notebook context. To do that on my cluster initialization-actions script I created the file `/etc/systemd/system/jupyter-notebook.service.d/myenv.conf` setting what I want on the PYTHONPATH  and it works fine when I create a python3 notebook, but when I create a Pyspark notebook the PYTHONPATH is overriden.

Digging a bit, I found out that the PYTHONPATH is overridden by script that generates the config json for Pyspark.

Here is a link to the line that overrides it: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/62559565e89cf7f998c6bda35c6fbff9e735ba84/jupyter/kernels/generate-pyspark.sh#L35

Am I missing something here?

**Comment by karth295** [comment]
Please try out the new [Jupyter optional component](https://cloud.google.com/dataproc/docs/tutorials/jupyter-notebook), which does not override PYTHONPATH, but instead just invokes the `pyspark` command.

The optional component works more like the [jupyter2 init action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/62559565e89cf7f998c6bda35c6fbff9e735ba84/jupyter2/), which never really took off. You can use `--image-version=1.3` for Python 2 or `--image-version=1.4` for Python 3. You can check out this blog post for instructions on installing extra packages: https://cloud.google.com/dataproc/docs/tutorials/python-configuration

P.S.  the init action is essentially in maintenance mode (sorry that isn't clearer in the README).
