### ISSUE TITLE
KeyError during conda install and environment activation

### ISSUE THREAD

**Issue by ToddMorrill** [GoogleCloudPlatform/dataproc-initialization-actions#53]
When I spin up a dataproc cluster and include bootstrap-conda.sh and install-conda-env.sh in my initialization actions, I'm getting the following error (which shows up on the master node and one of the worker nodes). It looks like the error is coming from the install-conda-env.sh script and it's throwing a KeyError.

Here is the output from the script:

echo $USER: 
echo $PWD: /
echo $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo $CONDA_BIN_PATH: 
echo $USER: 
echo $PWD: /
echo $PATH: /usr/local/bin/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo $CONDA_BIN_PATH: /usr/local/bin/miniconda/bin
No conda environment name specified, setting to 'root' env...
Attempting to create conda environment: root
Using Anaconda Cloud api site https://api.anaconda.org
conda environment root detected, skipping env creation...
Activating root environment...
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/activate.py", line 120, in main
    shelldict = shells[shell]
KeyError: 'dataproc-initia'

**Comment by bakebrain** [comment]
(similar) error when providing a name for the env (estest):

You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Attempting to append .bashrc to activate conda env at login...
grep: //.bashrc: No such file or directory
Appending .bashrc to activate conda env at login..
.bashrc successfully appended!
Activating estest environment...
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/conda/cli/activate.py", line 120, in main
    shelldict = shells[shell]
KeyError: 'dataproc-initia'

**Comment by ToddMorrill** [comment]
@bakebrain just in case you're spinning your wheels on this like I was, you can use the jupyter.sh file instead to get your conda environment setup. https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/jupyter and this set up with no errors for me.

**Comment by bakebrain** [comment]
@ToddMorrill thx - indeed this installs just fine!

**Comment by nehalecky** [comment]
@ToddMorrill, @bakebrain:

Am I working on an update for this init action that hopefully will resolve this issue, and had a quick question:
When using a dataproc cluster, what are some use cases that would require the ability to set a specific conda environment name (versus simply updating root environment with dependencies)? Any feedback would be much appreciated. Thank you!

**Comment by bakebrain** [comment]
@nehalecky I have yet to find a usecase that requires a custom name - mainly because i just provision and destroy afterwards - without e.g. having multiple environments on a cluster simultaneously.

Regarding the bug - the workaround that @ToddMorrill suggested worked nicely - I used a custom jupyter.sh that clones from a cloned init-repo and installed the packages required. But this is failing since today. Something must have changed - the cluster creation timed out and I believe certain anaconda paths are not set properly - I yet have to investigate more deeply.

**Comment by bakebrain** [comment]
this is the "new error" when running the vanilla jupyter initialisation script:

Finished bootstrapping via Miniconda...
echo $USER: 
echo $PWD: /
echo $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo $CONDA_BIN_PATH: 
echo $USER: 
echo $PWD: /
echo $PATH: /usr/local/bin/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo $CONDA_BIN_PATH: /usr/local/bin/miniconda/bin
No conda environment name specified, setting to 'root' env...
Attempting to create conda environment: root
Using Anaconda Cloud api site https://api.anaconda.org
conda environment root detected, skipping env creation...
Activating root environment...
./dataproc-initialization-actions/conda/install-conda-env.sh: line 40: activate: No such file or directory

**Comment by nehalecky** [comment]
@bakebrain, thanks much for the feedback. I am going to assume this is likely for a majority of users.

Re your issue, that's strange indeed. Nothing has changed in upstream master (e.g., this repo) recently that would have affected that. You're sure it that you are referencing in in cluster create (vs using a custom fork)? Occasionally we hit strange errors also on provisioning and simply try again. We'll get better at documenting those, soon, so we can discuss better.

I'll update here, soon.

**Comment by nehalecky** [comment]
Hey all! Please see our PR #58. Look forward to your feedback, thanks! :)

**Comment by bakebrain** [comment]
@nehalecky thanks - I will look into it tomorrow! I solved my issue in the meantime by just not calling

`source activate $CONDA_ENV_NAME` in my custom install-conda-env.sh - since the env is essentially "activated". It's a strange error since the very same setup always worked.
