### ISSUE TITLE
How to validated row count between GS(csv file) and BQ(Table) using python code - Google Cloud

### ISSUE THREAD

**Issue by pmiDataGen** [GoogleCloudPlatform/dataproc-initialization-actions#532]
I have a csv file in google storage, Have loaded that csv file to BigQuery Table before loading into BQ table i have to validate to row count should match andavoid  duplicate row insertion,

**Comment by functicons** [comment]
This question is not related to init actions. But does this [tutorial](https://cloud.google.com/dataproc/docs/tutorials/gcs-connector-spark-tutorial) help? It teaches how to read files in GCS. Also check Spark tutorials on how to read CSV files.
