### ISSUE TITLE
Examples in readme.me don't work in GCP SDK, only in CloudShell

### ISSUE THREAD

**Issue by stochastic1** [GoogleCloudPlatform/dataproc-initialization-actions#536]
When I'm using GCP SDK and following the example of spinning up a dataproc with a pip library, I run into either an error about regEx:

ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Metadata key ''PIP_PACKAGES' must match pattern [a-zA-Z0-9-_]{1,128}

or an unrecognized arguments error:

![image](https://user-images.githubusercontent.com/7283185/58130582-f7fe3180-7be1-11e9-89a3-d1ac7a0935fe.png)

However I have no such issue when I try this from cloudShell.

**Comment by medb** [comment]
Maybe you are using outdated version of GCP SDK?

**Comment by karth295** [comment]
From the error message, it seems like your Windows shell isn't correctly parsing the single quotes, and thinks that the first argument is `'PIP_PACKAGES`. It works in cloud shell because that's valid syntax in bash on linux. I'm not too familiar with windows, but maybe try double quotes?

**Comment by mroswald** [comment]
I can confirm, double quotes on windows shell did the trick for me.
