### ISSUE TITLE
Zeppelin Debian build files?

### ISSUE THREAD

**Issue by nevillelyh** [GoogleCloudPlatform/dataproc-initialization-actions#56]
Hi

We're trying to make a custom Zeppelin build and looking at https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/apache-zeppelin/zeppelin.sh, it's doing `apt-get install` from this repo: 
http://dataproc-bigtop-repo.storage.googleapis.com/

Just wondering if the Debian build files are publicly available somewhere?

**Comment by pmkc** [comment]
We build our packages using a fork of [Apache Bigtop](https://github.com/apache/bigtop), which we have not made publicly accessible at this time.

In the case of Zeppelin we have made no modifications from Bigtop HEAD (which uses pristine Zeppelin 0.5.6), aside from setting the versions of Spark and other components. You are welcome to use Bigtop, but I would suggest manually installing your build into /usr/local/ or /opt/ and optionally using checkinstall to create your own deb package.

**Comment by bzz** [comment]
@pmkc thank you for clarification!

So does that imply that in order to get a new version of Apache Zeppelin on DataProc you would need it to be added to Apache BigTop first?

Asking, as these is 0.6.1 coming with Spark 2.0 support and a [build-in interpreter for BigQuery](https://issues.apache.org/jira/browse/ZEPPELIN-1153).

**Comment by pmkc** [comment]
When 0.6.1 is released, we will upgrade it for (Dataproc image version 1.1)[https://cloud.google.com/dataproc/concepts/dataproc-versions], which currently has Zeppelin 0.6.0 with spark excluded.

The initialization action, which apt-get installs Zeppelin, will pick up the change. You are more than welcome to build Zeppelin at HEAD and edit the initialization action to use that in the meantime.

**Comment by bzz** [comment]
@pmkc just FYI, [Apache Zeppelin 0.6.1](http://zeppelin.apache.org/releases/zeppelin-release-0.6.1.html) has just been released

**Comment by evilsoapbox** [comment]
@bzz As a heads up, the initialization action should pull Zeppelin 0.6.1 on Dataproc 1.1 now.
