### ISSUE TITLE
INIT_ACTIONS_DIR: unbound variable

### ISSUE THREAD

**Issue by bencaine1** [GoogleCloudPlatform/dataproc-initialization-actions#569]
Starting up a cluster gives this error:

./dataproc-initialization-actions/jupyter/internal/setup-jupyter-kernel.sh: line 19: INIT_ACTIONS_DIR: unbound variable

Looks like this was probably caused by https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/4baa6ce5d0d3770492319d2d84339c5d32dc16e4.

**Comment by medb** [comment]
May you share command that you use to create a cluster?

**Comment by medb** [comment]
Most probably you are using an outdated Jupyter init actions from your own bucket, to solve this issue you need either to update your init action or set `INIT_ACTIONS_REPO` metadata value to your own GitHub repo that doesn't have latest changes.
