### ISSUE TITLE
dataproc initizialisation-actions failed to sync with gs://dataproc-initialization-actions

### ISSUE THREAD

**Issue by emeric-webedia** [GoogleCloudPlatform/dataproc-initialization-actions#576]
I have an issue when i try to start a dataproc cluster using the datalab initizialisation-actions.
It seems it fails while synchronising with gs://dataproc-initialization-actions. It copies 99% of the files and fails to copy a last file

I start my dataproc cluster with : 

```
gcloud dataproc clusters create spark-datalab-emeric --region europe-west1 --zone europe-west1-c --master-machine-type n1-standard-4 --master-boot-disk
-size 500 --num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 500 --image-version 1.3-deb9 --project allocine-bq --initialization-actions gs://dataproc-initialization-act
ions/datalab/datalab.sh
```

I get the following error 

```
ERROR: (gcloud.dataproc.clusters.create) Operation [projects/allocine-bq/regions/europe-west1/operations/ec49048c-4ac0-3330-b431-de51aa21954f] failed: Initialization action failed. Failed action'gs://dataproc-initialization-actions/datalab/datalab.sh', see output in: gs://dataproc-676a1688-8d8f-49c9-981b-2f21061a821f-europe-west1/google-cloud-dataproc-metainfo/6b0f0be5-c669-4fd5-ab92-
d67ba6310e8c/spark-datalab-emeric-m/dataproc-initialization-script-0_output.
```

In the log i see that it starts 

```
gsutil -m rsync -r gs://dataproc-initialization-actions /tmp/dataproc-init-actions-VNBH
Building synchronization state...
Starting synchronization...
Copying gs://dataproc-initialization-actions/.gitignore...
Copying gs://dataproc-initialization-actions/cloud-sql-proxy/__init__.py...
Copying gs://dataproc-initialization-actions/apache-zeppelin/README.MD...
Copying gs://dataproc-initialization-actions/bigdl/README.md...
```

its copying file

```
Copying gs://dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh...
/ [9/168 files][ 18.2 KiB/496.9 KiB]   3% Done                                  
/ [9/168 files][ 18.2 KiB/496.9 KiB]   3% Done                                  
Copying gs://dataproc-initialization-actions/conda/README.MD...
/ [10/168 files][ 19.6 KiB/496.9 KiB]   3% Done                                 
Copying gs://dataproc-initialization-actions/cloud-sql-proxy/test_cloud_sql.py...
/ [10/168 files][ 19.6 KiB/496.9 KiB]   3% Done                                 
/ [10/168 files][ 19.6 KiB/496.9 KiB]   3% Done                                 
Copying gs://dataproc-initialization-actions/cloud-sql-proxy/pyspark_metastore_test.py...
/ [10/168 files][ 19.6 KiB/496.9 KiB]   3% Done                                 
Copying gs://dataproc-initialization-actions/CONTRIBUTING.md...
/ [10/168 files][ 19.6 KiB/496.9 KiB]   3% Done   
```   

   

until 

```
Copying gs://dataproc-initialization-actions/zookeeper/README.MD...
/ [153/168 files][458.3 KiB/496.9 KiB]  92% Done                                
Copying gs://dataproc-initialization-actions/zookeeper/zookeeper.sh...
/ [153/168 files][458.3 KiB/496.9 KiB]  92% Done                                
/ [154/168 files][461.2 KiB/496.9 KiB]  92% Done                                
/ [155/168 files][463.7 KiB/496.9 KiB]  93% Done                                
/ [156/168 files][467.8 KiB/496.9 KiB]  94% Done                                
/ [157/168 files][467.8 KiB/496.9 KiB]  94% Done                                
-
- [158/168 files][473.8 KiB/496.9 KiB]  95% Done                                
- [159/168 files][480.0 KiB/496.9 KiB]  96% Done                                
- [160/168 files][481.0 KiB/496.9 KiB]  96% Done                                
- [161/168 files][485.3 KiB/496.9 KiB]  97% Done                                
- [162/168 files][485.3 KiB/496.9 KiB]  97% Done                                
- [163/168 files][487.8 KiB/496.9 KiB]  98% Done                                
- [164/168 files][493.0 KiB/496.9 KiB]  99% Done                                
- [165/168 files][493.0 KiB/496.9 KiB]  99% Done                                
- [166/168 files][496.9 KiB/496.9 KiB]  99% Done                                
- [167/168 files][496.9 KiB/496.9 KiB]  99% Done                                
CommandException: 1 files/objects could not be copied/removed.
```

**Comment by rodrigolazarinigil** [comment]
I am getting a similar problem today.

I ran this command:

`gcloud dataproc clusters create prt4i \
> --bucket xyz \
> --initialization-actions gs://dataproc-initialization-actions/connectors/connectors.sh,gs://dataproc-initialization-actions/jupyter/jupyter.sh \
> --metadata 'gcs-connector-version=1.9.11' \
> --metadata 'bigquery-connector-version=0.13.11' \
> --metadata 'JUPYTER_CONDA_PACKAGES="numpy pandas scipy"' \
> --region us-central1 \
> --zone us-central1-b \
> --num-workers 5 \
> --image-version 1.3-deb9 \
> --master-boot-disk-size 500GB \
> --master-boot-disk-type pd-standard \
> --master-machine-type n1-standard-8 \
> --worker-boot-disk-size 300GB \
> --worker-boot-disk-type pd-standard \
> --worker-machine-type n1-standard-32`

And the end of the log shows this:

`Copying gs://dataproc-initialization-actions/tez/test_tez.py...
- [141/168 files][428.9 KiB/496.9 KiB]  86% Done                                
- [142/168 files][428.9 KiB/496.9 KiB]  86% Done                                
Copying gs://dataproc-initialization-actions/zookeeper/README.MD...
Copying gs://dataproc-initialization-actions/user-environment/user-environment.sh...
Copying gs://dataproc-initialization-actions/util/utils.sh...
- [142/168 files][432.4 KiB/496.9 KiB]  87% Done                                
- [142/168 files][438.0 KiB/496.9 KiB]  88% Done                                
- [142/168 files][438.0 KiB/496.9 KiB]  88% Done                                
- [143/168 files][445.4 KiB/496.9 KiB]  89% Done                                
- [144/168 files][445.4 KiB/496.9 KiB]  89% Done                                
- [145/168 files][445.4 KiB/496.9 KiB]  89% Done                                
- [146/168 files][445.4 KiB/496.9 KiB]  89% Done                                
- [147/168 files][445.4 KiB/496.9 KiB]  89% Done                                
- [148/168 files][447.3 KiB/496.9 KiB]  90% Done                                
- [149/168 files][452.6 KiB/496.9 KiB]  91% Done                                
- [150/168 files][452.6 KiB/496.9 KiB]  91% Done                                
- [151/168 files][452.6 KiB/496.9 KiB]  91% Done                                
- [152/168 files][467.2 KiB/496.9 KiB]  94% Done                                
- [153/168 files][467.2 KiB/496.9 KiB]  94% Done                                
- [154/168 files][467.2 KiB/496.9 KiB]  94% Done                                
- [155/168 files][467.6 KiB/496.9 KiB]  94% Done                                
- [156/168 files][469.7 KiB/496.9 KiB]  94% Done                                
- [157/168 files][469.7 KiB/496.9 KiB]  94% Done                                
- [158/168 files][471.7 KiB/496.9 KiB]  94% Done                                
- [159/168 files][479.2 KiB/496.9 KiB]  96% Done                                
- [160/168 files][481.6 KiB/496.9 KiB]  96% Done                                
- [161/168 files][484.1 KiB/496.9 KiB]  97% Done                                
- [162/168 files][485.1 KiB/496.9 KiB]  97% Done                                
- [163/168 files][489.6 KiB/496.9 KiB]  98% Done                                
- [164/168 files][492.6 KiB/496.9 KiB]  99% Done                                
- [165/168 files][494.8 KiB/496.9 KiB]  99% Done                                
- [166/168 files][496.9 KiB/496.9 KiB]  99% Done                                
- [167/168 files][496.9 KiB/496.9 KiB]  99% Done                                
CommandException: 1 files/objects could not be copied/removed.`

**Comment by scottbreyfogle** [comment]
I also saw this problem. I was able to repro on my local machine as well. Take a look at the following:

```
$ mkdir /tmp/sync_folder
$ gsutil -m rsync -r gs://dataproc-initialization-actions /tmp/sync_folder
<lots of files copied, snipped>
CommandException: 1 files/objects could not be copied/removed.
```

```
$ gsutil -m rsync -r gs://dataproc-initialization-actions /tmp/sync_folder                                                                                                                                  
Building synchronization state...                                                                                                                                                                                                                                                         
Starting synchronization...
Copying gs://dataproc-initialization-actions/jupyter/jupyter.sh...
Copying gs://dataproc-initialization-actions/jupyter//jupyter.sh...
[Errno 2] No such file or directory  0% Done
CommandException: 1 files/objects could not be copied/removed.
```

```
$ gsutil ls gs://dataproc-initialization-actions/jupyter
gs://dataproc-initialization-actions/jupyter/
gs://dataproc-initialization-actions/jupyter/README.MD
gs://dataproc-initialization-actions/jupyter/__init__.py
gs://dataproc-initialization-actions/jupyter/jupyter.sh
gs://dataproc-initialization-actions/jupyter/launch-jupyter-interface.sh
gs://dataproc-initialization-actions/jupyter/test_jupyter.py
gs://dataproc-initialization-actions/jupyter//
gs://dataproc-initialization-actions/jupyter/internal/
gs://dataproc-initialization-actions/jupyter/kernels/
```

That stray slash as a file/directory name is concerning to me.

**Comment by medb** [comment]
There was wrongly synced file `gs://dataproc-initialization-actions/jupyter//jupyter.sh` (with 2 slashes) that broke rsync, after it's deletion it works again.
