### ISSUE TITLE
`python` init action does not work on 1.4+ or if pyspark is configured to use a conda env

### ISSUE THREAD

**Issue by karth295** [GoogleCloudPlatform/dataproc-initialization-actions#607]
This is the core of the [pip-install init action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/python/pip-install.sh):

```
easy_install pip
pip install --upgrade ${PACKAGES}
```

Note that `easy_install pip` will install `pip` in the system python environment, and then `pip install <packages>` installs packages within the system python environment.

However, Dataproc 1.4+ installs miniconda by default, Dataproc 1.3+ offers an ANACONDA optional component, and many users run the old conda init action in this repository. In all of these cases, `pypsark` will use the conda environment, rather than the system python environment.

So instead, the init action should discover which python environment pyspark uses, and install packages there. When conda is installed, pip is installed as well, so you can just run `/opt/conda/<env>/bin/pip install <packages>`

**Comment by functicons** [comment]
This should have been fixed by https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/commit/470db29c91c1aabd29ef800e1f6a89871eca88d6#diff-23eeeb4347bdd26bfc6b7ee9a3b755dd
