### ISSUE TITLE
conda pinned to old version

### ISSUE THREAD

**Issue by birdsarah** [GoogleCloudPlatform/dataproc-initialization-actions#614]
Conda is pinned to `4.5.*`. As a result its unupgradeable without manually altering conda-meta. New conda `4.7.*` has had numerous upgrades and is considerably more performant, consider upgrading.

**Comment by medb** [comment]
Conda init action has a `MINICONDA_VERSION` parameter that allows to override pinned Miniconda version:
```bash
gcloud dataproc clusters create $CLUSTER --image-version 1.2 \
    --metadata MINICONDA_VERSION=4.7.10 \
    --initialization-actions gs://dataproc-initialization-actions/conda/bootstrap-conda.sh
```
