### ISSUE TITLE
apt update failed with invalid signature EXPKEYSIG

### ISSUE THREAD

**Issue by functicons** [GoogleCloudPlatform/dataproc-initialization-actions#619]
`sudo apt update` is failing: 

```
W: Failed to fetch http://storage.googleapis.com/dataproc-bigtop-repo/1_4_deb9_20190808_014700-RC01/dists/dataproc/InRelease  The following signatures were invalid: EXPKEYSIG 567D794D3610E553 Google Inc. <dataproc-feedback@google.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

The signing key for the Dataproc Bigtop repo has expired, but installing packages should continue to work, e.g.:

```
$ sudo apt install kafka-server -y
```

For now, just ignore the error for `apt update`.

**Comment by tomstockton** [comment]
This caused Lab 5 in the 'Leveraging Unstructured Data' Qwiklabs course to fail.

I worked around by editing my own version of the script and adding `--allow-unauthenticated` to https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/datalab/datalab.sh#L129

I'm not sure what the correct fix should be though.

**Comment by functicons** [comment]
`--allow-unauthenticated` is the workaround until we have a new Bigtop release.

**Comment by chimera92** [comment]
sudo apt update --allow-unauthenticated
sudo apt --allow-unauthenticated update 

Both of these still don't work..

`gn:1 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian stretch InRelease
Err:2 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian stretch Release
  407  authenticationrequired
Hit:3 http://storage.googleapis.com/dataproc-bigtop-repo/1_4_deb9_20190808_014700-RC01 dataproc InRelease
Hit:4 http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease
Hit:5 http://packages.cloud.google.com/apt google-cloud-monitoring-stretch InRelease
Hit:7 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
Err:3 http://storage.googleapis.com/dataproc-bigtop-repo/1_4_deb9_20190808_014700-RC01 dataproc InRelease
  The following signatures were invalid: EXPKEYSIG 567D794D3610E553 Google Inc. <dataproc-feedback@google.com>
Hit:9 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease
Hit:6 http://security-cdn.debian.org stretch/updates InRelease
Hit:10 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
Ign:8 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:11 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:12 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease
Hit:13 http://cdn-fastly.deb.debian.org/debian stretch Release
Reading package lists... Done
E: The repository 'http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://storage.googleapis.com/dataproc-bigtop-repo/1_4_deb9_20190808_014700-RC01 dataproc InRelease: The following signatures were invalid: EXPKEYSIG 567D794D3610E553 Google Inc. <dataproc-feedback@google.com>`

**Comment by cjac** [comment]
Another slightly less dangerous solution might be to add the `[trusted=yes]` attribute to the `sources.list` file containing the storage.googleapis.com respository:

```
deb [trusted=yes] http://storage.googleapis.com/dataproc-bigtop-repo/1_4_deb9_20190808_014700-RC01 dataproc
```

**Comment by cjac** [comment]
It may also be required to use the `[allow-Insecure=yes]` attribute in the same way until the packages are signed by a non-expired key.

https://manpages.debian.org/buster/apt/sources.list.5.en.html

**Comment by functicons** [comment]
For existing clusters with expired Bigtop GPG key, run the following command to extend the expiration date:

`curl http://storage.googleapis.com/dataproc-bigtop-repo/1_3_deb9_20190918_012600-RC01/archive.key | sudo apt-key add -`

It works for all cluster versions (e.g., 1.4).

**Comment by functicons** [comment]
Closing this issue as the new images have been released.
