### ISSUE TITLE
how to use this in the cluster-config.json for installing PIP_PACKAGES? 

### ISSUE THREAD

**Issue by mikekuzak** [GoogleCloudPlatform/dataproc-initialization-actions#628]
Can't find any documentation which would show how to use the PIP_PACKAGES feature in the dataproc cluster-config.json. 

Tried this without luck: 
`    "gceClusterConfig": {
      "zoneUri": "us-east4-a",
      "metadata": {
        "PIP_PACKAGES": "pyarrow==0.14.1"
      },`

Any advice pls ? 
Thanks

**Comment by medb** [comment]
It's documented here: https://cloud.google.com/dataproc/docs/tutorials/python-configuration#image_python_environments
