### ISSUE TITLE
dr-elephant is not building

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudPlatform/dataproc-initialization-actions#631]
Error:
```
[info] *** 6 TESTS FAILED ***
[error] Failed: Total 492, Failed 8, Errors 0, Passed 483, Skipped 1
[error] Failed tests:
[error] 	com.linkedin.drelephant.tuning.PSOParamGeneratorTest
[error] 	com.linkedin.drelephant.util.SparkUtilsTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 40 s, completed Oct 2, 2019 5:51:13 PM
Build failed...
+ unzip /root/dr-elephant/dist/dr-elephant-2.1.7.zip -d /root/dr-elephant/dist/
unzip:  cannot find or open /root/dr-elephant/dist/dr-elephant-2.1.7.zip, /root/dr-elephant/dist/dr-elephant-2.1.7.zip.zip or /root/dr-elephant/dist/dr-elephant-2.1.7.zip.ZIP.
+ err 'Build step failed'
++ date +%Y-%m-%dT%H:%M:%S%z
+ echo '[2019-10-02T17:51:13+0000]: Build step failed'
[2019-10-02T17:51:13+0000]: Build step failed
+ return 1
```

**Comment by aniket486** [comment]
Thanks for the feedback. Can you contribute a test to make sure this initialization-action does not break over time?

**Comment by ChethanUK** [comment]
> Thanks for the feedback

It's already fixed, I just busy.. I may be wrong with my words...

But, I strongly feel as Dataproc community it will be nice to have:

1. Slack Channel
2. Place where we can request for features
3. Monthly community Meetings (Online) LIKE in Tensorflow [Meetings](https://calendar.google.com/calendar/embed?src=tensorflow.org_14t769n89qhsps949c3l0nhd9c%40group.calendar.google.com)
 
Thanks!.

**Comment by ChethanUK** [comment]
@medb Dr Elephant script is taking more than 30minutes... 

```bash
Initialization action timed out. Failed action 'gs://{BUCKET}/init/presto-inits/dr-elephant.sh', 
```

Can we reduce by uploading the building from git source?

**Comment by medb** [comment]
> Can we reduce by uploading the building from git source?

You can use [Dataproc Custom Image](https://cloud.google.com/dataproc/docs/guides/dataproc-images) with pre-installed Dr Elephant if start-up time is critical for you.
