### ISSUE TITLE
`pip-install.sh` does not work on 1.3-ubuntu18 images

### ISSUE THREAD

**Issue by karth295** [GoogleCloudPlatform/dataproc-initialization-actions#646]
E.g. `gcloud beta dataproc clusters create kpal13-prod-ubu --image-version=1.3-ubuntu18 --initialization-actions gs://dataproc-initialization-actions/python/pip-install.sh --metadata PIP_PACKAGES=requests`

```
++ /usr/share/google/get_metadata_value attributes/PIP_PACKAGES
+ readonly PACKAGES=requests
+ PACKAGES=requests
+ main
+ [[ -z requests ]]
+ easy_install pip
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 13: easy_install: command not found
```

But note that `pip` is already installed, even though `easy_install` is not:

```
$ pip

Usage:   
  pip <command> [options]

...
```

In theory, the init action could be fixed by having something like:

```
if ! type pip > /dev/null; then
  easy_install pip
fi
```

**Comment by Rebecasarai** [comment]
Hello, I'm getting this error in version: "2.0.28-ubuntu18".

...`"--initialization-actions" "{CODE_GCS_URI}/init_script.sh",``...


My nitialization-action sscript:

```python
#!/bin/bash

set -exo pipefail

readonly PACKAGES=$(/usr/share/google/get_metadata_value attributes/PIP_PACKAGES || true)

function main() {
  if [[ -z "${PACKAGES}" ]]; then
    echo "ERROR: Must specify PIP_PACKAGES metadata key" 
    exit 1
  fi

  easy_install pip
  pip install --upgrade ${PACKAGES}
}

main
```
