### ISSUE TITLE
HBase Init script /bin/bash bad interpreter

### ISSUE THREAD

**Issue by TheMatrix97** [GoogleCloudPlatform/dataproc-initialization-actions#666]
Seems HBase init script is not working properly...
I executed: 
```bash
gcloud dataproc clusters create test-hbase2 \
    --initialization-actions gs://my-playground/scripts/hbase.sh \
    --num-masters 1 --master-machine-type=n1-standard-1 --master-boot-disk-size=50 \
    --num-workers 2 --worker-machine-type=n1-standard-1 --worker-boot-disk-size=50 \
    --preemptible-worker-boot-disk-size=20
```

I'm getting the following error in master and worker nodes:
```bash
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: /bin/bash^M: bad interpreter: No such file or directory
```

Is bash not available?? Anyone has any idea of which could it be the problem?
Thank you in advance!

**Comment by medb** [comment]
Can you try to reproduce this issue with Dataproc-provided init action and larger VMs (`n1-standard-1` is too small for HBase):
```bash
gcloud dataproc clusters create test-hbase2 \
    --initialization-actions gs://dataproc-initialization-actions/hbase/hbase.sh \
    --num-masters 1 --master-machine-type=n1-standard-4 --master-boot-disk-size=100 \
    --num-workers 2 --worker-machine-type=n1-standard-4 --worker-boot-disk-size=100 \
    --preemptible-worker-boot-disk-size=100
```

**Comment by TheMatrix97** [comment]
> 
> 
> Can you try to reproduce this issue with Dataproc-provided init action and larger VMs (`n1-standard-1` is too small for HBase):
> 
> ```shell
> gcloud dataproc clusters create test-hbase2 \
>     --initialization-actions gs://dataproc-initialization-actions/hbase/hbase.sh \
>     --num-masters 1 --master-machine-type=n1-standard-4 --master-boot-disk-size=100 \
>     --num-workers 2 --worker-machine-type=n1-standard-4 --worker-boot-disk-size=100 \
>     --preemptible-worker-boot-disk-size=100
> ```

Yep, your command worked like charm! certainly n1-standard-1 is too small. Thank you! I'm closing this issue :)

**Comment by TheMatrix97** [comment]
The error was that I created the script using windows... Windows and Linux use different characters for declaring new lines or the end of file.... Before upload use dos2unix or similar
