### ISSUE TITLE
Unable Accessing Notebooks within Folders on Jupyter UI

### ISSUE THREAD

**Issue by philip-zelichenko** [GoogleCloudPlatform/dataproc-initialization-actions#679]
When generating Jupyter notebooks within folders in the Jupyter UI, trying to access these notebooks result in "Server error: error"; Any notebooks under folders generated in the UI aren't accessible through the UI.

![image](https://user-images.githubusercontent.com/16638019/69982899-59388300-14ea-11ea-8f27-85754f54fac0.png)

**Comment by functicons** [comment]
Did you actually use the init action or optional component to create the cluster?

**Comment by functicons** [comment]
@philip-zelichenko I'm closing this issue now, reopen please if that doesn't solve your issue.
