### ISSUE TITLE
extra spark packages in datalab

### ISSUE THREAD

**Issue by bodschut** [GoogleCloudPlatform/dataproc-initialization-actions#76]
Hi,

The datalab init script works great, but I was wondering how to make additional spark packages (like e.g. the avro package from databricks) available in the datalab notebook. In the jupyter init script you can add them to the PYSPARK_SUBMIT_ARGS. Can we do something similar here?

Thanks

**Comment by dovy** [comment]
+1   Please make this happen.

**Comment by pmkc** [comment]
This is fixed in #101 using the same solution as the Jupyter initialization action.
