### ISSUE TITLE
Secure Jupyter Notebook with simple authentication

### ISSUE THREAD

**Issue by senthilaru** [GoogleCloudPlatform/dataproc-initialization-actions#80]
The jupyter notebook initialization action is working good as expected. Mostly, we would need that to be authenticated/secured while launching in the internet.

Required a metadata property to specify notebook password, similar to the `PORT` option exposed during cluster creation.

The task may involve creating private-public key/certificate and set those to the jupyter configuration property, and set the default password.

**Comment by kirtanechiron** [comment]
Yeah it's not working for me either. This sucks...

**Comment by pmkc** [comment]
I'm not exactly sure what you mean by private keys. An optional password sounds possible.

It is generally not advisable to open any ports in the Dataproc network to the internet. Instead it is recommended [you access Web UIs via proxies](https://cloud.google.com/dataproc/docs/concepts/cluster-web-interfaces). Given that it doesn't seem that simple authentication would offer much benefit.

**Comment by senthilaru** [comment]
Password option would be helpful. For Https,  we would need default self-signed certificates created on the fly or option to link the existing cert files .

**Comment by pmkc** [comment]
Apparently setting the token is support, but not documented with --metadata=JUPYTER_AUTH_TOKEN=... from #81. I'd take a PR for https support, but I doubt we'll get around to any time soon.

Updating the documentation now.

**Comment by pmkc** [comment]
Updated docs in #128
